module.exports=[
    // key hệ thống
    {key:"Personal",value:"Personal"},
    {key:"StrategicObject",value:"Strategic object"},
    {key:"Goals",value:"Goals"},
    {key:"Duration",value:"Duration"},
    {key:"PercentCompleted",value:"Percent completed"},
    {key:"StrategicManagement",value:"Strategic management"},
    {key:"ProjectTaskManagement",value:"Project task management"},
    {key:"DepartmentTaskManagement",value:"Department task management"},
    {key:"NewGoals",value:"New goals"},
    {key:"NewStrategyGoals",value:"New strategic goals"},
    {key:"Progress",value:"Progress"},
    {key:"CheckObtainedStrategic",value:"obtained strategic"},
    {key:"DoYouWantCheckObtainedStrategic",value:"Do you want check obtained to strategic: {{title}}"},
    {key:"DoYouWantCheckObtainedObject",value:"Do you want check obtained to object: {{title}}"},
    {key:"FailureAction",value:"Failure action"},
    {key:"DataIsNotExists",value:"Data is not exists"},
    {key:"OrderBy",value:"Order by"},
    {key:"Filter",value:"Filter"},
    {key:"AddTask",value:"Add task"},
    {key:"Creator",value:"Creator"},
    {key:"AddProject",value:"Add project"},
    {key:"UpdateProjectInformation",value:"Update project information"},
    {key:"DeleteThisProject",value:"Delete this project"},
    {key:"DoYouWantDeleteProject",value: "Do you want delete project: {{title}}?"},
    {key:"DoYouWantDeleteTask",value: "Do you want delete task: {{title}}?"},
    {key:"DoYouWantDeleteObject",value: "Do you want delete goals: {{title}}?"},
    {key:"DoYouWantDeleteStrategicObject",value: "Do you want delete strategic goals: {{title}}?"},
    {key:"DoYouWantDeleteDocument",value: "Do you want delete document: {{title}}?"},
    {key:"TaskICreated",value:"Task I created"},
    {key:"MyTask",value:"My task"},
    {key:"SummaryOfWorkStatus",value:"Summary of work status"},
    {key:"TaskGrowthChart",value:"Task growth chart"},
    {key:"ProjectSummary",value:"Project summary"},
    {key:"ProjectGrowthChart",value:"Project growth chart"},
    {key:"Prioritized",value:"Prioritized"},
    {key:"PriorityLevel",value:"Priority"},
    {key:"Critical",value:"Critical"},
    {key:"High",value:"High"},
    {key:"Medium",value:"Medium"},
    {key:"Low",value:"Low"},
    {key:"Express",value:"Express"},
    {key:"Emergency",value:"Emergency"},
    {key:"Normal",value:"Normal"},
    {key:"FindTasksByName",value:"Find tasks by name"},
    {key:"ProjectImplementationInformation",value:"Project implementation information"},
    {key:"InformationOnDepartmentActivities",value:"Information on department activities"},
    {key:"ReTypeTheFollowingPhrase",value:"Re-type the following phrase"},
    {key:"TypeHere",value:"Type here"},
    {key:"StartProject",value:"Start project"},
    {key:"CloseProject",value:"Close project"},
    {key:"DoYouWantToStartProject",value:"Do you want to start project: {{title}}"},
    {key:"DoYouWantToCloseProject",value:"Do you want to close project: {{title}}"},
    {key:"TheProjectHasEnded",value:"The project has ended"},
    {key:"DeployingPlan",value:"Deploying plan"},
    {key:"TheProjectHasntStartedYet",value:"The project hasn't started yet"},
    {key:"Obtained",value:"Obtained"},
    {key:"Document",value:"Document"},
    {key:"ProjectDocument",value:"Project document"},
    {key:"Wiki",value:"Wiki"},
    {key:"AddDocument",value:"Add document"},
    {key:"InputContentHere",value:"Input content here"},
    {key:"FindDocumentsByName",value:"Find documents by name"},
    {key:"UpdateDocument",value:"Update document"},
    {key:"Views",value:"Views"},
    {key:"Viewers",value:"Viewers"},
    {key:"Love",value:"Love"},
    {key:"removedAttachment",value:"removed attachment"},
    {key:"addedAttachment",value:"uploaded attachment"},
    {key:"NewDepartment",value:"New department"},
    {key:"NewWorkflow",value:"New workflow"},
    {key:"UpdateWorkflowInformation",value:"Update workflow information"},
    {key:"FindWorkflowByName",value:"Find workflow by title"},
    {key:"AddCheckList",value:"Add check list"},
    {key:"CheckListofTask",value:"Check list of task"},
    {key:"InputCheckListName",value:"input check list name"},
    {key:"TypeCommentHere",value:"Type comment here"},
    {key:"NewChildDepartment",value:"New child department"},
    {key:"UpdateInformationDepartment",value:"Update information department"},
    {key:"NoUserSelectedYet",value:"No user selected yet"},
    {key:"NoDepartmentSelectedYet",value:"No department selected yet"},
    {key:"YouHaveNewNotify",value:"You have a new notify"},
    {key:"NewNoticeNeedsApproval",value:"New notice needs approval"},
    {key:"YouHaveBeenAssignedATask",value:"You have been assigned a job"},
    {key:"GotANewTaskToKeepTrackOf",value:"Got a new job to keep track of"},
    {key:"TheTaskIsDone",value:"The task is done"},
    {key:"TheTaskIsCompleted",value:"The task is completed"},
    {key:"ThereIsANewComment",value:"There is a new comment"},
    {key:"YouJustJoinedANewProject",value:"You just joined a new project"},
    {key:"TheProjectHasStarted",value:"The project has started"},
    {key:"ThereIs1DocumentThatNeedsApproval",value:"There is 1 document that needs approval"},
    {key:"YourDocumentHasBeenApproved",value:"Your document has been approved"},
    {key:"TheDocumentHasBeenApproved",value:"The document has been approved"},
    {key:"YourDocumentHasBeenRejected",value:"Your document has been rejected"},
    {key:"TheDocumentHasBeenRejected",value:"The document has been rejected"},
    {key:"ThereIs1LeaveFormThatNeedsApproval",value:"There is 1 leave form that needs approval"},
    {key:"YourLeaveFormHasBeenApproved",value:"Your leave form has been approved"},
    {key:"TheLeaveFormHasBeenApproved",value:"The leave form has been approved"},
    {key:"YourLeaveFormHasBeenRejected",value:"Your leave form has been rejected"},
    {key:"TheLeaveFormHasBeenRejected",value:"The leave form has been rejected"},
    {key:"YouAreGrantedANewJourneyTimeForm",value:"Your are granted a new journey time form"},
    {key:"YourJourneyTimeFormPermitApplicationHasBeenCancelled",value:"Your journey time form permit application has been cancelled"},
    {key:"FlowDesign",value: "Flow design"},
    {key:"AddTaskWorkflow",value: "Add task workflow"},
    {key:"UpdateTaskWorkflow",value: "Update task workflow"},
    {key:"AddFolder",value: "Add New Folder"},
    {key:"AddFile",value: "Add New File"},
    {key:"LastUpdate",value: "Last Update"},
    {key:"FileSize",value: "File Size"},
    {key:"Version",value: "Version"},
    {key:"FolderEmpty",value: "This Folder Is Empty"},
    {key:"ShareFolder",value: "Share Folder"},
    {key:"UpdateFolder",value: "Update Folder"},
    {key:"UpdateFile",value: "Update File"},
    {key:"DoYouWantDeleteFolder",value: "Do you want delete folder: {{name}}?"},
    {key:"DoYouWantDeleteFile",value: "Do you want delete file: {{name}}?"},
    {key:"TaskName",value: "Task name"},
    {key:"ClickToOpenThisTaskOnYourPortal",value: "Click to open this task on your portal"},
    {key:"Return",value: "Return"},
    {key:"Resubmit",value: "Resubmit"},
    {key:"Singed",value: "Singed"},
    {key:"Unsigned",value: "Unsigned"},
    {key:"SignHistory",value: "Sign history"},
    {key:"Submitter",value: "Submitter"},
    {key:"WaitingForProgressing",value: "Waiting for progressing"},
    {key:"ExecutingASignature",value: "Executing a signature"},
    {key:"Are you sure you approve this document for signature",value: "Are you sure you approve this document for signature?"},
    {key:"Are you sure you confirm that received this",value: "Are you sure you confirm that received this?"},
    {key:"Are you sure you reject this document for signature",value: "Are you sure you reject this document for signature?"},
    {key:"Are you sure you return this document for signature",value: "Are you sure you return this document for signature?"},
    {key:"Are you sure you resubmit this document for signature",value: "Are you sure you resubmit this document for signature?"},
    {key:"Are you sure you sign this document",value: "Are you sure you sign this document {{filename}}?"},
    {key:"Format of signing in text",value: "Format of signing in text"},
    {key:"Permission: Role - Department",value: "Permission: {{role}} - {{department}}"},
    {key:"Import StudyPlan",value: "Import StudyPlan"},
    {key:"Import ExamSchedule",value: "Import Exam Schedule"},
    {key:"File Name",value: "File Name"},
    {key:"Date Upload",value: "Date Upload"},
    {key:"UpdateConfigTable",value: "Update Config Table"},
    {key:"TaskManagement",value: "Task Management"},
    {key:"Text",value:"Text"},
    {key:"Signature",value:"Signature"},
    {key:"TemplateCustom",value:"Template (Custom)"},
    {key:"FormatUploadedFile",value:"Format uploaded file"},
    {key:"InputTagName",value:"Input tag name"},
    {key:"Signing file (upload)",value:"Signing file (upload)"},
    {key:"Signing file (auto generated)",value:"Signing file (auto generated)"},
    {key:"Fill in the signing file information",value:"Fill in the signing file information"},
    {key:"Input content",value:"Input content"},
    {key:"Preview",value:"Preview"},
    {key:"Quotation mark",value:"Quotation mark"},
    {key:"Format",value:"Format"},
    {key:"Select directory",value:"Select directory"},
    {key:"Signatures/Quotation marks cannot be duplicated in case All Approval",value:"Signatures/Quotation marks cannot be duplicated in case All Approval"},
    {key:"Workflow is missing Signatures/Quotation marks",value:"Workflow is missing Signatures/Quotation marks"},
    {key:"Created date",value:"Created date"},
    {key:"Created by",value:"Created by"},
    {key:"Content",value:"Content"},
    {key:"Status",value:"Status"},
    {key:"Abbreviation",value:"Abbreviation"},
    {key:"Input abbreviation",value:"Input abbreviation"},
    {key:"AbbreviationIsExist",value:"Abbreviation is exist"},
    {key:"Code",value:"Code"},
    {key:"File type",value:"File type"},
    {key:"File generated by template",value:"File generated by template"},
    {key:"User upload manually",value:"User upload manually"},
    {key:"Tag (in the file)",value:"Tag (in the file)"},
    {key:"Tag name",value:"Tag name"},
    {key:"Tag type",value:"Tag type"},
    {key:"e.g. sign_headofdep",value:"e.g. sign_headofdep"},
    {key:"Add Signature/Quotation mark tag",value:"Add Signature/Quotation mark tag"},
    {key:"Directory",value:"Directory"},
    {key:"Signing file require the following tags",value:"Signing file require the following tags"},
    {key:"Task",value:"Task"},
    {key:"HeadTask",value:"Head Task"},
    {key:"Invalid file format",value:"Invalid file format"},
    {key:"File is missing required tags",value:"File is missing required tags"},
    {key:"Create new Workflow play",value:"Create new Workflow play"},
    {key:"GanttChart",value:"Gantt Chart"},
    {key:"Overview",value:"Overview"},
    {key:"TaskAddNewNotification",value:"Add New Notification"},
    {key:"ThereIsANewProof",value:"There is a new proof"},
    {key:"ProofOfCompletion",value:"Proof of completion"},
    {key:"UpdateProofOfCompletion",value:"Upload proof of completion"},
    {key:"ProofFileRequired",value:"File proof of completion is required"},
    {key:"MaxProofFilesUpload",value:"Maximum 5 proof files allowed to upload"},
    {key:"File size must not exceed", value: "File size must not exceed {{size}}"},
    {key:"Download",value: "Download"},
    {key:"TaskType",value:"Type of Task"},
    {key:"All",value:"All"},
    {key:"Label",value:"Label"},
    {key:"Department/Project",value:"Department/Project"},
    {key:"attachments/appendices",value:"Attachments/Appendices"},
    {key:"SearchByNameOrFileCode",value:"Search by name or file code"},
    {key:"FileCode",value:"File Code"},
    {key:"CreationTime",value:"Creation Time"},
    {key:"ProfileDetails",value:"Profile Details"},
    {key:"AddTransferTicket",value:"Add Transfer Ticket"},
    {key:"Are you sure you want to cancel this task?",value:"Are you sure you want to cancel this task?"},
    {key:"CancellationReason",value:"Cancellation Reason"},
    {key:"AllDepartments",value:"All Departments"},
    {key:"SomeDepartments",value:"Some Departments"},
    {key:"Add Task by template for project",value:"Add task by template for project"},
    {key:"Add Task by template for department",value:"Add task by template for department"},
    {key:"LabelManagementForDepartment",value:"Label Management for Department"},
    {key:"AddNewMajorLabel",value:"Add major label"},
    {key:"AddNewMinorLabel",value:"Add minor label"},
    {key:"UpdateMajorLabel",value:"Update Major Label"},
    {key:"UpdateMinorLabel",value:"Update Minor Label"},
    {key:"NewTitleOfLabel",value:"New title of label"},
    {key:"MajorLabel",value:"Major label"},
    {key:"DownloadSampleFile",value:"Download sample file"},
    {key:"IncommingDispatchBook",value:"Incomming dispatch book"},
    {key:"OutgoingDispatchBook",value:"Outgoing dispatch book"},
    {key:"IntegrationWithWorkflowPlay",value:"Integration with workflow play"},
    {key:"Early",value:"Completed ahead of schedule"},
    {key:"Late",value:"Completed overdue"},
    {key:"RecurringTask",value:"Recurring Task"},
    {key:"Add recurring task for department",value:"Add recurring task for department"},
    {key:"Cycle",value:"Cycle"},
    {key:"TaskManagementByCycle",value:"Task Management By Cycle"},
    {key:"Series",value:"Series"},
    {key:"Pause",value:"Paused"},
    {key:"day",value:"day"},
    {key:"week",value:"week"},
    {key:"month",value:"month"},
    {key:"year",value:"year"},
    {key:"PauseTask",value:"Pause Task"},
    {key:"ResumeTask",value:"Resume Task"},
    {key:"CancelTask",value:"Cancel Task"},
    {key:"Are you sure you want to pause this task?",value:"Are you sure you want to pause this task?"},
    {key:"Are you sure you want to resume this task?",value:"Are you sure you want to resume this task?"},
    {key:"TaskCode",value:"Task code"},
    {key:"Year the briefcase was created",value:"Year the briefcase was created"},
    {key:"Add head task",value:"Add head task"},
    {key:"HasBeenJustReleasedBy",value:"has been just released by"},
    {key:"WorkflowNodeOnSchedule", value: "On Schedule"},
    {key:"WorkflowNodeGonnaLate", value: "Gonna Late"},
    {key:"WorkflowNodeOverDue", value: "Over Due"},
    {key:"RequestCode",value:"Request Code"},
    {key:"DocumentToBeCopied",value:"Document to be copied"},
    {key:"SentDate",value:"Sent date"},
    {key:"UsageTime",value:"Usage time"},
    {key:"NormTime", value: "Norm Time"},
    {key:"Deadline", value: "Deadline"},
    {key:"BusinessDay", value: "Business Day"},
    {key:"NotYet", value: "Not yet"},
    {key:"Project", value: "Project"},
    {key:"Transfer ticket",value:"Transfer ticket"},
    {key:"HostPerson", value:"Host"},
    {key:"SortBy", value:"Sort by"},
    {key:"SortingOrder", value:"Sorting order"},
    {key:"Ascending(A->Z)", value:"Ascending (A->Z)"},
    {key:"Descending(Z->A)", value:"Descending(Z->A)"},
    {key:"Are you sure you ack this event for",value: "Are you sure you {{type}} this event for student ID: {{studentId}}?"},
    {key:"Coordinator", value:"Coordinator"},
    {key:"Document number and notation", value:"Document number and notation"},
    {key:"Input Document number and notation", value:"Input Document number and notation"},
    {key:"Agency promulgate", value:"Agency promulgate"},
    {key:"Input Agency promulgate", value:"Input Agency promulgate"},
    {key:"Department receives to know", value:"Department receives to know"},
    {key:"No department receives to know", value:"No department receives to know"},
    {key:"Selected", value:"Selected"},
    {key:"Resolving tasks", value:"Resolving tasks"},
    {key:"No resolving tasks", value:"No resolving tasks"},
    {key:"Add resolving task", value:"Add resolving task"},
    {key:"Task summary", value:"Task summary"},
    {key:"WaitingForApproval", value:"Waiting for approval"},
    {key:"Edit", value:"Edit"},
    {key:"Forward to the head of the school office", value:"Forward to the head of the school office"},
    {key:"Send to board of directors", value:"Send to board of directors"},
    {key:"Send to departments", value:"Send to departments"},
    {key:"Accept", value:"Accept"},
    {key:"Mark as read", value:"Mark as read"},
    {key:"ForwardToHeadOfOffice", value:"Forward to head of office"},
    {key:"ForwardToBOD", value:"Forward to bod"},
    {key:"WaitingForReview", value:"Waiting for review"},
    {key:"Transferred", value:"Transferred"},
    {key:"WaitingForAccept", value:"Waiting for accept"},
    {key:"Unread", value:"Unread"},
    {key:"Read", value:"Read"},
    {key:"ForwardToDepartments", value:"Send to departments"},
    {key:"ResponseRead", value:"Read"},
    {key:"ResponseAccept", value:"Accept"},
    {key:"ResponseReject", value:"Reject"},
    {key:"You have an dispatch arrived _code_ that needs to be approved", value:"You have an dispatch arrived {{code}} that needs to be approved"},
    {key:"You have an dispatch arrived _code_ that needs to be reviewed", value:"You have an dispatch arrived {{code}} that needs to be reviewed"},
    {key:"ForwardNotifyToViewOnlyDepartments", value:"You have an dispatch arrived {{code}} that needs to be viewed"},
    {key:"ForwardHeadTaskToDepartments", value:"You have an dispatch arrived {{code}} that needs to be processed"},
    {key:"_department_ has accepted to process the dispatch arrived _code_", value:"{{department}} has accepted to process the dispatch arrived {{code}}"},
    {key:"_department_ has rejected to process the dispatch arrived _code_", value:"{{department}} has rejected to process the dispatch arrived {{code}}"},
    {key:"_department_ has read the dispatch arrived _code_", value:"{{department}} has read the dispatch arrived {{code}}"},
    {key:"DoYouWantReleaseODB", value:"Do you want to release this outgoing dispatch?"},
    {key:"Attachment of the Incoming Document", value:"Attachment of the Incoming Document "},
    {key:"Add Related File", value:"Add Related File"},
    {key:"ResponsibleWork", value:"Responsible work"},
    {key:"CoordinationWork", value:"Coordination work"},
    {key:"SupervisionWork", value:"Supervision work"},
    {key:"AllowsUsersToChooseTheDestination", value:"Allows users to choose the destination"},
    {key:"Handling methods", value:"Handling methods"},
    {key:"Flexible", value:"Flexible"},
    {key:"Fixed", value:"Fixed"},
    {key:"Confirm receipt of the notification", value:"Confirm receipt of the notification"},
    {key:"Grant permission to use the incoming dispatch feature", value:"Grant permission to use the incoming dispatch feature"},
    {key:"Right to view official dispatches other than work-related official dispatches", value:"Right to view official dispatches other than work-related official dispatches"},
    {key:"Only incoming dispatches related to assigned work can be viewed", value:"Only incoming dispatches related to assigned work can be viewed"},
    {key:"View official dispatches at the unit you are working at", value:"View official dispatches at the unit you are working at"},
    {key:"Dispatch belongs to all departments", value:"Dispatch belongs to all departments"},
    {key:"Dispatches at some specific departments", value:"Dispatches at some specific departments"},
    {key:"Not yet assigned", value:"Not yet assigned"},
    {key:"Car Name", value:"Car Name"},
    {key:"License Plate", value:"License Plate"},
    {key:"Seating Capacity", value:"Seating Capacity"},
    {key:"UpdateCarInformation", value:"Update Car Information"},
    {key:"CarList", value:"Car List"},
    {key:"CarRegistration", value:"Car Registration"},
    {key:"Destination", value:"Destination"},
    {key:"Input Destination", value:"Input Destination"},
    {key:"Number of people", value:"Number of people"},
    {key:"Input Number of people", value:"Input number of people"},
    {key:"Start date", value:"Start date"},
    {key:"End date", value:"End date"},
    {key:"Back date", value:"Back date"},
    {key:"Department", value:"Department"},
    {key:"Description", value:"Description"},
    {key:"Register", value:"Register"},
    {key:"CarReview", value:"Car/card vehicle Review"},
    {key:"CarConfirm", value:"Car/card vehicle Confirm"},
    {key:"CardDelivery", value:"Card Delivery"},
    {key:"DoYouWantApprove", value: "Do you want to approve {{title}}?"},
    {key:"DoYouWantReject", value: "Do you want to reject {{title}}?"},
    {key:"DoYouWantClose", value: "Do you want to close {{title}}?"},
    {key:"carApprove", value: "Car Approve"},
    {key:"Closed", value: "Closed"},
    {key:"Close", value:"Close"},
    {key:"reviewer_approved", value:"Reviewer approved"},
    {key:"reviewer_rejected", value:"Reviewer rejected"},
    {key:"manager_closed", value:"Closed"},
    {key:"end", value:"Close"},
    {key:"manager_approved", value:"Approved"},
    {key:"manager_reject", value:"Rejected"},
    {key:"head_approved_car", value:"Approved"},
    {key:"head_approved_card", value:"Approved"},
    {key:"card_received", value:"Card vehicle received"},
    {key:"cancelled", value:"Cancelled"},
    {key:"manager_card_received", value:"Card vehicle received"},
    {key:"card_delivery", value:"Card vehicle delivered"},
    {key:"card_return", value:"Card vehicle returned"},
    {key:"card_return_tooltip", value:"Card Return"},
    {key:"card_delivery_tooltip", value:"Card Delivery"},
    {key:"card_receive_tooltip", value:"Card Receive"},
    {key:"cancel", value:"Cancel"},
    {key:"RejectReason", value:"Reject reason:"},
    {key:"Card vehicle", value:"Select card vehicle:"},
    {key:"Car", value:"Car"},
    {key:"Input the submission department", value:"Input the submission department"},
    {key:"You dont have permission to do this", value:"You do not have permission to do this"},
    {key:"Size", value:"Size"},
    {key:"InsertMeetingRoom", value:"Insert meeting room"},
    {key:"UpdateMeetingRoom", value:"Update meeting room"},
    {key:"IsUse", value:"Is use"},
    {key:"UnUse", value:"Un use"},
    {key:"InputCodeOfMeetingRoom", value:"Input code of meeting room"},
    {key:"InputTitleOfMeetingRoom", value:"Input title of meeting room"},
    {key:"InputSizeOfMeetingRoom", value:"Input size of meeting room"},
    {key:"InvalidRuleMeetingRoom", value:"You do not have permission to use"},
    {key:"MeetingRoomSchedule", value:"Meeting room schedule"},
    {key:"CurrentLeadTasks", value:"Current lead tasks"},
    {key:"CarTicketManagement", value:"Car Ticket Management"},
    {key:"Need to review", value:"Need to review"},
    {key:"PendingRecalled", value:"Processing recall"},
    {key:"ApprovedRecallByDepartmentLeader", value:"The department head approved the recall"},
    {key:"started project", value:"started project"},
    {key:"RoomRegistration", value:"Room Registration"},
    {key:"LectureHallClassroom", value:"Lecture hall, classroom"},
    { key: "AreYouSureYouApproveThisNotify", value: "Are you sure you approve this notify?" },
    { key: "AreYouSureYouRejectThisNotify", value: "Are you sure you reject this notify?" },
    {key:"Recall",value: "Recall"},
    {key:"Recalled",value: "Recalled"},
    {key:"ApprovedDate",value: "ApprovedDate"},
    {key:"StatusProcess", value:"Status process"},
    {key:"closed project", value:"closed project"},
    {key:"CreatedNotify", value:"Created notify"},
    {key:"RegisteredRecall", value:"Registered for recall"},
    {key:"NewsType", value:"News type"},
    {key:"NotificationRecipients", value:"Notification recipients"},
    {key:"RejectRecall", value:"Reject recall"},
    {key:"ApproveRecall", value:"Approve recall"},
    {key:"ApproveRecallRequestForThisNotify", value:"Do you want to approve the request to recall this notice ?"},
    {key:"RejectRecallRequestForThisNotify", value:"Do you want to reject the recall request for notify {{title}} ?"},
    {key:"InformationDepartment",value:"Information department"},
    // event_calendar
    {key:"Participant", value:"Participants"},
    {key:"PersonInCharge", value:"Person in charge"},
    {key:"Type", value:"Type"},
    {key:"OfflineOnSite", value:"Offline on site"},
    {key:"OfflineOffSite", value:"Offline off site"},
    {key:"Online", value:"Online"},
    {key:"CarRegister", value:"Register car"},
    { key: "Loading", value: "Loading" },
    { key:"RoomRegister", value:"Register room"},
    {key:"EventCalendarRegister", value:"Register for work schedule"},
    {key:"EventCalendarRegisterRecall", value:"Register to withdraw work schedule"},
    { key:"Location", value:"Location"},
    { key: "DepartmentApproved", value: "Department Head Approved" },
    { key: "DepartmentApprovedRecall", value: "Department Head Approved Recall" },
    { key: "DepartmentRejectedRecall", value: "Department Head Rejected Recall" },
    { key: "PendingApproval", value: "Pending department head approved" },
    { key: "RejectedByDept", value: "Department head rejected" },
    { key: "PendingApprovedByDept", value: " Pending other department head approved" },
    { key: "RejectedByHeadDept", value: "Other department head rejected" },
    { key: "PendingApprovedByHeadDept", value: "Pending for department head approval" },
    { key: "FinalReject", value: "Rejected by final approver" },
    { key: "FinalApproval", value: "Final approval" },
    { key: "Archived", value: "Archived" }  ,
    { key: "DepartmentReturned", value: "Department Head Returned" },
    { key: "DepartmentRejected", value: "Department Head Rejected" },
    { key: "ManagerApproved", value: "Calendar Manager Approved" },
    { key: "ManagerReturned", value: "Calendar Manager Returned" },
    { key: "ManagerRejected", value: "Calendar Manager Rejected" },
    { key: "OrganizationApproved", value: "Leader Approved" },
    { key: "OrganizationReturned", value: "Leader Returned" },
    { key: "OrganizationReject", value: "Leader Rejected" },
    { key: "RequestCancel", value: "Request Cancel" },
    { key: "Cancelled", value: "Cancelled" },
    { key: "MeetingLink", value: "Meeting Link" },
    { key: "EventCalendar", value: "Event Calendar" },
    { key: "EventManagement", value: "Event List"},
    { key: "EventNeedToHandle", value: "Needs Handling"},
    { key: "EventResponsibleUnit", value: "Belongs to Responsible Unit"},
    { key: "EventHandled", value: "Event handled"},
    { key: "EventCreated", value: "Created"},
    { key: "EventPersonallyInvolved", value: "Personally Involved"},
    {key:"Task is already completed", value:"Task is already completed"},
    { key: "WorkTripCreation", value: "Event Calendar List" },
    { key: "WorkTripAll", value: "All" },
    { key: "WorkTripAssigned", value: "Need to process" },
    { key: "FinalApprovalTitle", value: "Final Approval" },
    { key: "RejectTitle", value: "Do you want to reject this event schedule?" },
    { key: "DoYouWantApprove", value: "Do you want to approve?" },
    { key: "ApprovalTitle", value: "Approval" },
    {key:"Task is cancelled", value:"The job has been cancelled"},
    {key:"Task has not been started yet", value:"Task has not been started yet"},
    {key:"fast job processing", value:"fast job processing"},
    {key:"Document to be approved", value:"Document to be approved"},
    {key:"Document Name/ Workflow Name", value:"Document Name/ Workflow Name"},
    {key:"Composer/Submitter", value:"Composer/Submitter"},
    {key:"FindDocumentByName", value:"Find document by name"},
    {key:"Sign", value:"Sign"},
    {key:"Approve", value:"Approve"},
    {key:"Processing time", value:"Processing time"},
    {key:"Responsible Department/Project", value:"Responsible Department/Project"},
    {key:"Find task by name and code", value:"Find task by name and code"},
    {key:"Challenge", value:"Challenge"},
    {key:"AddChallenge", value:"Add Challenge"},
    {key:"AddChallengeSuccess", value:"Add Challenge Success"},
    {key:"AddChallengeAt", value:"Add Challenge at"},
    {key:"ChallengeResolved", value:"Challenge Resolved"},
    {key:"GuidToResolveChallenge", value:"Guid To Resolve Challenge"},
    {key:"Add comment", value:"Add comment"},
    {key:"Display task of all departments", value:"Display task of all departments"},
    {key:"Default is only display task of departments youre leading", value:"Default is only display task of departments you're leading"},
    {key:"Latest comment", value:"Latest comment"},
    {key:"DoYouWantReceiveCard", value:"Do you want to confirm that you have received your vehicle card?"},
    {key:"DoYouWantDeliveryCard", value:"Do you want to delivery the vehicle card?"},
    {key:"DoYouWantReturnCard", value:"Do you want to return the vehicle card?"},
    {key:"chooseDriver", value:"Choose driver"},
    {key:"Grant permission to manage the incoming dispatch feature", value:"Grant permission to manage the incoming dispatch feature"},
    {key:"Grant permission to lead the incoming dispatch feature", value:"Grant permission to lead the incoming dispatch feature"},
    {key:"This is the right for the organization s secretary", value:"This is the right for the organization's secretary"},
    {key:"This is the right reserved for the organization s clerical leader", value:"This is the right reserved for the organization's clerical leader"},
    {key:"Not allow", value:"Not allow"},
    {key:"Right to approve in lead level", value:"Right to approve in lead level"},
    {key:"For department is working", value:"For department is working"},
    {key:"All departments", value:"All departments"},
    {key:"For specific departments", value:"For specific departments"},
    {key:"This is the right reserved for board of directors", value:"This is the right reserved for board of directors"},
    {key:"Right to accept task", value:"Right to accept task"},
    {key:"This is the right reserved for department leaders", value:"This is the right reserved for department leaders"},
    {key:"Reminder of work due date", value:"Reminder of work due date"},
    {key:"Newsletter", value:"Newsletter"},
    {key:"Find newsletter by title", value:"Find newsletter by title"},
    {key:"Work schedule/ Meeting room/ Vehicle to be approved", value:"Work schedule/ Meeting room/ Vehicle to be approved"},
    {key:"Find by title", value:"Find by title"},
    {key:"Find by title and code", value:"Find by title and code"},
    {key:"YouHaveReminded", value:"You have reminded"},
    {key:"YouHaveNotReminded", value:"You have not reminded"},
    {key:"DeadlineReminder", value:"Deadline reminder"},
    {key:"YouHaveCommented", value:"You have commented"},
    {key:"YouHaveNotCommented", value:"You have not commented"},
    {key:"ReminderSuccessful", value:"Reminder successful"},
    {key:"YouJustCommented", value:"You just commented"},
    {key:"Allow to approve event in depatment level", value:"Allow to approve event in depatment level"},
    {key:"CarCalendar", value:"Car Schedule"},
    {key:"Car_Date", value:"Car/ Date"},
    {key:"enterTheAmountSpent", value:"Enter the amount spent"},
    {key:"invoice", value:"Invoice"},
    {key:"isTrueInfoConfirm", value:"Verify the truth of the information above"},

    {key:"Responsible Department", value:"Responsible department"},
    {key:"NumberOfParticipants", value:"Number of participants"},
    //Registration room
    {key:"Registered", value:"Registered"},
    {key:"Confirmed", value:"Confirmed"},
    {key:"Approved", value:"Approved"},
    {key:"ChooseRoom", value:"ChooseRoom"},
    {key:"Vehicle", value:"Vehicle"},
    {key:"WorkSchedule", value:"WorkSchedule"},
    {key:"PhoneNumber", value:"PhoneNumber"},
    {key:"SizeRoomNotEnough", value:"{{roomName}} has only {{roomSize}} seats!"},
    {key:"RejectedRegistration", value:"Rejected Registration!"},
    {key:"ApproredRegistration", value:"Approred Registration"},
    {key:"Default is display all registration", value:"Default is display all registration"},
    {key:"ConfirmReject", value:"Confirm reject"},
    {key:"Delete", value:"Delete"},
    {key:"TitleRegistrationRoom", value:"Title registration meeting room"},
    {key:"Start date use", value:"Start date use"},
    {key:"TypeRoom", value:"Type room"},
    {key:"Room", value:"Room"},
    {key:"ParticipateDepartments", value:"Departments participate"},
    {key:"OtherParticipants", value:"Other participants"},
    {key:"RejectApproval", value:"Reject ppproval"},
    {key:"ConfirmRequetCancel", value:"Confirm requet cancel"},
    {key:"ConfirmDelete", value:"Confirm delete"},
    {key:"person", value:"person"},
    {key:"ConfirmedRoomRecall", value:"Confirmed room recall"},
    {key:"PersonAction", value:"Person action"},
    {key:"Action", value:"Action"},
    {key:"Reason", value:"Reason"},
    {key:"Time", value:"Time"},
    {key:"Title", value:"Title"},

    {key:"ConfirmedEventCalendarRecall", value:"Management confirmed the recall."},
    {key:"RegisterEventCalendarSuccess", value:"Registered business schedule successfully"},
    {key:"UpdateInfoSuccess", value:"Information updated successfully"},
    {key:"Deleted", value:"Deleted"},
    {key:"Requestcanceled", value:"Request canceled"},
    {key:"NumdayShow", value:"Number of days displayed"},

    {key:'ChooseDepartment',value:'Choose department'},
    {key:'End date cannot be less than or equal to start date',value:'End date cannot be less than or equal to start date'},
    {key:'RequestCancelSuccess',value:'Request cancel success'},
    {key:'ChooseHost', value:'Choose host'},
    {key:'Accept registration successfully',value:'Accept registration successfully'},
    {key:"NotToExceedDays", value:"Not to exceed {{numDay}} days"},
    {key:'AddOtherHost', value:'Add other hosts'},
    {key:'OtherHost', value:'Other host'},
    {key:'RecommendedService', value:'Recommended service'},
    {key:'TechnicalSupport', value:'Technical support'},
    {key:'TeaBreak', value:'Tea-break'},
    {key:'Flow', value:'Flow'},
    {key:"approve", value:"approve"},
    {key:"RegisterRoomSCheduleSuccess", value:"Register room sCheduleSuccess"},
    {key:"UpdateRoomSCheduleSuccess", value:"Update room sheduleSuccess"},
    {key:"Not choose room", value:"Room not selected yet"},
    {key:"Rejected", value:"Rejected"},
    {key:"Compose a news", value:"Compose a news"},
    {key:"Temporary Department", value:"Temporary Department"},
    {key:"Board", value:"Board"},
    {key:"Department Code", value:"Department Code"},
    {key:"You have run out of tasks to handle", value:"You have run out of tasks to handle"},
    {key:"Publish", value:"Publish"},
    { key: "MarkAsComplete", value: "Mark as complete" },
    { key: "MarkDone", value: "Mark done" },
    {key:"MarkDoneSuccess", value:"Mark done success"},
    {key:"Department prepare content", value:"Đơn vị chuẩn bị nội dung"},


    {key:"Published", value:"Published"},
    {key:"CarRegistrationList", value:"Car registration list"},
    {key:"Card not returned", value:"Card not returned"},
    {key:"Pick up time", value:"Pick up time"},
    {key:"Time to go", value:"Time to go"},
    {key:"Location List", value:"Localtion list"},
    {key:"Location Name", value:"Localtion name"},
    {key:"Starting place", value:"Starting place"},
    {key:"Passenger", value:"Passenger"},
    {key:"Register car", value:"Register car"},
    {key:"Department proposed", value:"Department proposed"},
    {key:"Proposed", value:"Proposed"},
    {key:"Participating departments", value:"Participating departments"},
    {key: "Number of the participarnt must greater than or equal to", value: "Number of the participarnt must greater than or equal to{{number}}"},
    {key:"DepartmentLeaderApproved", value:"Department leader approved"},
    {key:"VehicleManagementSpecialistApproved", value:"Vehicle manager approved"},
    {key:"LeadApproved", value:"Leader approved"},
    {key:"CardManagerApproved", value:"Card manager approved"},
    {key:"CardManagerAssignedCard", value:"Card manager asigned card"},
    {key:"DepartmentReceivedCard", value:"Department received card"},
    {key:"DepartmentReturnedCard", value:"Department returned card"},
    {key:"CompletedCard", value:"Completed"},
    {key:"RequestedRecall", value:"Requested recall"},
    {key:"DepartmentLeaderApprovedRecall", value:"Department leader approved recall"},
    {key:"VehicleManagementSpecialistApprovedRecall", value:"Vehicle manager approved recall"},
    {key:"Pick up time cannot be less than or equal to time to go", value:"Pick up time  cannot be less than or equal to time to go"},
    {key:"AreYouSureApproveThisRegistration", value:"Are you sure to approve this registration ?"},
    {key:"AreYouSureRejectThisRegistration", value:"Are you sure to reject this registration ?"},
    {key:"AreYouSureEditCardCarThisRegistration", value:"Are you sure edit card car this registration ?"},
    {key:"AreYouSureConfirmReturnCardCarThisRegistration", value:"Are you sure confirm return card car this registration ?"},
    {key:"AreYouSureCancelThisRegistration", value:"Are you sure cancel this registration ?"},
    {key:"ProcessRegistration", value:"Process registraion"},
    {key:"DeleteRegistration", value:"Delete registraion"},
    {key:"You need to note for request cancel", value:"You need to note for request cancel"},
    {key:"You can note for accept", value:"You can note for accept"},
    {key:"You can note for edit card car", value:"You can note for edit card"},
    {key:"You need to note for reject", value:"You need to note for reject"},
    {key:"You need to note for return card", value:"You need to note for return card"},
    {key:"You need to note for assign card", value:"You need to note for assign card"},
    {key:"You can note for receive card", value:"You need to note for receive card"},
    {key:"You need to note for cancel registration", value:"You need to note for cancel registration"},
    {key:"You can note for return card", value:"You can note for return card"},
    {key:"Assign a car", value:"Assign a car"},
    {key:"Assign a credit card", value:"Assign a credit card"},
    {key:"Driver", value:"Driver"},
    {key:"Transportation allowance", value:"Transportation allowance"},
    {key:"CreditCard", value:"Credit card"},
    {key:"CreditCardName", value:"Name of credit card"},

    {key:"CreditCardNumber", value:"Number of credit card"},
    {key:"CreditCardBussy", value:"Credit card busy"},
    {key:"CreditCardActive", value:"Credit card active"},
    {key:"ChangeCardCredit", value:"Change card credit"},
    {key:"ConfirmReceiveCard", value:"Confirm receive card"},
    {key:"AreYouSureConfirmReceiveCardCreditThisRegistration", value:"Are you sure you confirm receive card credit this registration?"},
    {key:"ReturnCard", value:"Return card"},
    {key:"UploadFileInvoice", value:"Upload file invoice"},
    {key:"ICertifyThatTheAboveStatementsAreTrue", value:"I certify that the above information is true"},
    {key:"TheAmountSpent", value:"The Amount spent"},
    {key:"NumberKm", value:"Number of kilometers"},
    {key:"You can note for manager receive card", value:"You can note for manager receive card"},
    {key:"Input number card", value:"Input number card"},
    {key:"Invoices", value:"Invoices"},
    {key:"AmountSpent", value:"AmountSpent"},
    {key:"Km", value:"Kilometers"},

    {key:"ApprovedLeaderDepartment", value: "Approved leader department"},
    {key:"RejectedLeaderDepartment", value: "Rejected leader department"},
    {key:"ApprovedCarManagement", value: "Approved car management"},
    {key:"RejectedCarManagement", value: "Rejected car management"},
    {key:"ApprovedLead", value: 'Approved lead'},
    {key:"ApprovedRecallLead", value: 'Approved recall lead'},
    {key:"RejectedLead", value: "Rejected lead"},
    {key:"RejectedRecallLead", value: "Rejected recall lead"},
    {key:"ApprovedCardManagement", value: "Approved card management"},
    {key:"RejectedCardManagement", value: "Rejected card management"},
    {key:"CreatorReceivedCard", value: "Creator received card"},
    {key:"CreatorReturnCard", value: "Creator return card"},
    {key:"ManagerReceivedCard", value: "Manager received card"},
    {key:"DepartmentApprovedCancel", value: "Department approved cancel"},
    {key:"CreatorCancel", value: "Creator cancel"},
    {key:"ShowMore", value: "Show more"},
    {key:"CarScheduleUse", value: "Car schedule use"},
    {key:"Allday", value: "Allday"},
    {key:"Early in the day", value: "Early in the day"},
    {key:"Until the end of the day", value: "Until the end of the day"},

    {key:"Need you to review and approve registration car", value: "Need you to review and approve registration car"},
    {key:"Department leader approved. Need you to review and confirm registration car", value: "Department leader approved. Need you to review and confirm registration car"},
    {key:"Manager car confirmed. Need you to review and approve registration car", value: "Manager car confirmed. Need you to review and approve registration car"},
    {key:"Lead approved. Need you to review and approve registration car", value: "Lead approved. Need you to review and approve registration car"},
    {key:"Manager card approved. Need you to review and receive card credit", value: "Manager card approved. Need you to review and receive card credit"},
    {key:"Department returned card. Need you to review and confirm received card", value: "Department returned card. Need you to review and confirm received card"},
    {key:"approved the car registration", value: "approved the car registration"},
    {key:"Management card confirm received card credit", value: "Management card confirm received card credit"},
    {key:"rejected the car registration", value: "Car registration denied"},

    {key:"ManagementCarApproved", value: "Management car approved"},
    {key:"ManagementCarRejected", value: "Management car rejected"},
    {key:"LeadRejected", value: "Lead rejected"},
    {key:"ManagementCardApprove", value: "Management card approve"},
    {key:"ManagementCardRejected", value: "Management card rejected"},
    {key:"ManagementCardChangeCard", value: "Management card change card"},
    {key:"ManagementCardAssignCard", value: "Management card assign card"},
    {key:"CreatorReturnedCard", value: "Creator returned card"},
    {key:"ManagingReceivedCard", value: "Managing received card"},
    {key:"MarkAsCompleteSuccess", value: "Mark as complete success"},

    {key:"AreYouSureApprovalThisRegistration", value: "Are you sure approval this registration?"},
    {key:"AreYouSureRequestCancelThisRegistration", value: "Are you sure request cancel this registration?"},
    {key:"AreYouSureApprovalRecallThisRegistration", value: "Are you sure approval recall this registration?"},
    {key:"AreYouSureRejectRecallThisRegistration", value: "Are you sure reject recall this registration?"},

    {key:"TimeEvent", value: "Time to start"},
    {key:"AddressEvent", value: "Meeting location/room"},
    {key:"DayEvent", value: "Day/Date"},
    {key:"Hour", value: "Hour"},
    {key:"LevelEvent", value: "Level"},
    {key:"Level_1", value: "Whole school"},
    {key:"Level_2", value: "In the department"},
    {key:"car", value: "Car"},
    {key:"room", value: "Room"},
    {key:"event_calendar", value: "Work schedule"},
    {key:'State', value:'State'},
    {key:'All Department', value:'All Department'},

    {key:"registration_room_approve", value:"Approved"},
    {key:"registration_room_approve_recall",value:"Approved request cancel"},
    {key:"registration_room_reject",value:"Rejected"},
    {key:"registration_room_reject_recall",value:"Rejected request cancel"},
    {key:"registration_room_request_cancel",value:"Request canceled"},
    {key:"registration_room_update",value:"Information updated"},
    {key:"registration_room_create",value:"Created"},

    {key:"Card/Car", value:"Card/Car"},
    {key:"Show column", value:"Display column"},
    {key:"ChangeCar", value:"Change car"},
    {key:"ChangeCard", value:"Change card"},
    {key:"ChangeDriver", value:"Change driver"},
    {key:"LeadApprovedAndChange", value:"Lead approved and change"},
    {key:"LeadExternalApproved", value:"Lead external approved"},
    {key:"LeadExternalRejected", value:"Lead external rejected"},
    {key:"DepartmentApprovedAndChange", value:"Department approved and change"},
    { key: 'ApproveTransferTicket', value: 'Approve Transfer Ticket' },
    { key: 'RejectTransferTicket', value: 'Reject Transfer Ticket' },
    {key:"DoYouWantUpdateProgressTask",value: "Do you want update progress task: {{title}}?"},
    { key: 'EditAndApprove', value: 'Edit and approve' },

    { key: 'I agree', value: 'I agree' },
    { key: 'I refuse', value: 'I refuse' },
    { key: 'Incorrect information', value: 'Incorrect information' },
    { key: 'Out of cars', value: 'Out of cars' },
    { key: 'Out of cards', value: 'Out of cards' },
    { key: 'ManagementApproved', value: 'Management approved' },
    { key: 'ManagementApprovedRecall', value: 'Management approved recall' },
    { key: 'ManagementRejected', value: 'Management rejected' },
    { key: 'ManagementRejectedRecall', value: 'Management rejected recall' },
    { key: 'Lead external approved. Need you to review and receive card credit', value: 'Lead external approved. Need you to review and receive card' },
    { key: 'addComment', value: 'Add comment' },
    { key: 'updateComment', value: 'Update comment'},
    { key: 'I approve', value: 'I approve' },
    { key: 'Well done, I approve', value: 'Well done, I approve' },
    { key: 'Processed', value: 'Processed' },
    { key: 'Done Approval', value: 'Done Approval' },
    { key: 'Complete Approval', value: 'Complete Approval' },
    {key: "WorkIsRepeatedCyclically", value: "Work is repeated cyclically"},
    {key: "RoomCode", value: "Room code"},
    {key: "RoomName", value:"Room name"},
    { key: "Start", value: "Start"},
    { key: "End", value: "End"},
    { key: "Comment", value: "Comment"},
    { key: "There is a news notify that has not been viewed yet", value: "There is a news notify that has not been viewed yet"},
    {key:"You can note for approval", value:"You can note for approval"},
    { key: "CarManagement", value: "Car management"},
    { key: "Reject Recall", value: "Reject recall"},
    { key: "My calendar", value: "My calendar"},

    { key: "NumberCard", value: "Number card"},
    { key: "ManageExternal", value: "ManageExternal"},
    { key: "ExportToExcelManage", value: "Export to excel external"},
];
