module.exports=[
    {key:"Personal",value:"Cá nhân"},
    {key:"StrategicObject",value:"Mục tiêu chiến lược"},
    {key:"Goals",value:"Mục tiêu"},
    {key:"Duration",value:"Thời hạn"},
    {key:"PercentCompleted",value:"Phần trăm hoàn thành"},
    {key:"StrategicManagement",value:"Quản trị chiến lược"},
    {key:"ProjectTaskManagement",value:"Quản lý công việc dự án"},
    {key:"DepartmentTaskManagement",value:"Quản lý công việc phòng ban"},
    {key:"NewGoals",value:"Thêm mục tiêu"},
    {key:"NewStrategyGoals",value:"Thêm mục tiêu chiến lược"},
    {key:"Progress",value:"Tiến độ"},
    {key:"CheckObtainedStrategic",value:"Đánh dấu đã đạt được chiến lược"},
    {key:"DoYouWantCheckObtainedStrategic",value:"Bạn có muốn đánh dấu đã đạt được chiến lược {{title}}"},
    {key:"DoYouWantCheckObtainedObject",value:"Bạn có muốn đánh dấu đã đạt được mục tiêu {{title}}"},
    {key:"FailureAction",value:"Xử lý thất bại"},
    {key:"DataIsNotExists",value:"Dữ liệu không tồn tại"},
    {key:"OrderBy",value:"Sắp xếp theo"},
    {key:"Filter",value:"Lọc dữ liệu"},
    {key:"AddTask",value:"Thêm công việc"},
    {key:"Creator",value:"Người tạo"},
    {key:"AddProject",value:"Thêm mới dự án"},
    {key:"AddTransferTicket",value:"Thêm mới phiếu chuyển"},
    {key:"UpdateProjectInformation",value:"Cập nhật thông tin dự án"},
    {key:"DeleteThisProject",value:"Xoá dự án"},
    {key:"DoYouWantDeleteProject",value: "Bạn có muốn xoá dự án: {{title}} không?"},
    {key:"DoYouWantDeleteTask",value: "Bạn có muốn xoá công việc: {{title}} không?"},
    {key:"DoYouWantUpdateProgressTask",value: "Bạn có muốn cập nhập tiến độ công việc: {{title}} không?"},
    {key:"DoYouWantDeleteObject",value: "bạn có muốn xoá mục tiêu: {{title}}? không"},
    {key:"DoYouWantDeleteStrategicObject",value: "Bạn có muốn xoá mục tiêu chiến lược: {{title}} không?"},
    {key:"DoYouWantDeleteDocument",value: "Bạn có muốn xoá tài liệu : {{title}} không?"},
    {key:"TaskICreated",value:"Công việc tôi đã tạo"},
    {key:"MyTask",value:"Công việc của tôi"},
    {key:"SummaryOfWorkStatus",value:"Tóm tắt tình hình công việc"},
    {key:"TaskGrowthChart",value:"Biểu đồ phát triển công việc"},
    {key:"ProjectSummary",value:"Tóm tắt dự án"},
    {key:"ProjectGrowthChart",value:"Biểu đồ phát triển dự án"},
    {key:"Prioritized",value:"Ưu tiên"},
    {key:"PriorityLevel",value:"Độ ưu tiên"},
    {key:"Critical",value:"Nghiêm trọng"},
    {key:"High",value:"Quan trọng"},
    {key:"Medium",value:"Trung bình"},
    {key:"Low",value:"Thấp"},
    {key:"Express",value:"Hoả tốc"},
    {key:"Emergency",value:"Khẩn"},
    {key:"Normal",value:"Bình thường"},
    {key:"FindTasksByName",value:"Tìm công việc theo tên"},
    {key:"ProjectImplementationInformation",value:"Thông tin thực hiện dự án"},
    {key:"InformationOnDepartmentActivities",value:"Thông tin hoạt động phòng ban"},
    {key:"ReTypeTheFollowingPhrase",value:"Nhập lại cụm từ sau"},
    {key:"TypeHere",value:"Nhập vào đây"},
    {key:"StartProject",value:"Bắt đầu dự án"},
    {key:"CloseProject",value:"Đóng dự án"},
    {key:"DoYouWantToStartProject",value:"Bạn có muốn bắt đầu dự án: {{title}}"},
    {key:"DoYouWantToCloseProject",value:"Bạn có muốn đóng dự án: {{title}}"},
    {key:"TheProjectHasEnded",value:"Dự án đã kết thúc"},
    {key:"DeployingPlan",value:"Dự án đang được triển khai"},
    {key:"TheProjectHasntStartedYet",value:"Dự án chưa bắt đầu"},
    {key:"Obtained",value:"Hoàn thành"},
    {key:"Document",value:"Tài liệu"},
    {key:"ProjectDocument",value:"Tài liệu dự án"},
    {key:"Wiki",value:"Kho tài liệu"},
    {key:"AddDocument",value:"Thêm mới tài liệu"},
    {key:"InputContentHere",value:"Nhập nội dung tại đây"},
    {key:"FindDocumentsByName",value:"Tìm tài liệu theo tên"},
    {key:"UpdateDocument",value:"Cập nhật thông tin tài liệu"},
    {key:"Views",value:"Lượt xem"},
    {key:"Viewers",value:"Số người xem"},
    {key:"Love",value:"Yêu thích"},
    {key:"removedAttachment",value:"đã xoá đính kèm"},
    {key:"addedAttachment",value:"đã thêm đính kèm"},
    {key:"NewDepartment",value:"Thêm mới phòng ban"},
    {key:"NewWorkflow",value:"Thêm mới quy trình"},
    {key:"UpdateWorkflowInformation",value:"Cập nhật thông tin quy trình"},
    {key:"FindWorkflowByName",value:"Tìm quy trình theo tên"},
    {key:"AddCheckList",value:"Thêm check list"},
    {key:"CheckListofTask",value:"Check list của công việc"},
    {key:"InputCheckListName",value:"Nhập tên check list"},
    {key:"TypeCommentHere",value:"Nhập bình luận tại đây"},
    {key:"NewChildDepartment",value:"Thêm phòng ban con"},
    {key:"UpdateInformationDepartment",value:"Cập nhật thông tin phòng ban"},
    {key:"NoUserSelectedYet",value:"Chưa chọn người dùng nào"},
    {key:"NoDepartmentSelectedYet",value:"Chưa chọn phòng ban nào"},
    {key:"YouHaveNewNotify",value:"Bạn có 1 thông báo mới"},
    {key:"NewNoticeNeedsApproval",value:"Thông báo mới cần phê duyệt"},
    {key:"YouHaveBeenAssignedATask",value:"Bạn được giao 1 công việc"},
    {key:"GotANewTaskToKeepTrackOf",value:"Có một công việc mới cần bạn theo dõi"},
    {key:"TheTaskIsDone",value:"Công việc được thực hiện xong"},
    {key:"TheTaskIsCompleted",value:"Công việc đã hoàn tất"},
    {key:"ThereIsANewComment",value:"Có một bình luận mới"},
    {key:"YouJustJoinedANewProject",value:"Bạn vừa tham gia một dự án mới"},
    {key:"TheProjectHasStarted",value:"Dự án đã bắt đầu"},
    {key:"ThereIs1DocumentThatNeedsApproval",value:"Có 1 văn bản cần phê duyệt"},
    {key:"YourDocumentHasBeenApproved",value:"Đơn trình ký của bạn đã được phê duyệt"},
    {key:"TheDocumentHasBeenApproved",value:"Đơn trình ký đã được phê duyệt"},
    {key:"YourDocumentHasBeenRejected",value:"Đơn trình ký của bạn đã bị bác bỏ"},
    {key:"TheDocumentHasBeenRejected",value:"Đơn trình ký đã bị bác bỏ"},
    {key:"ThereIs1LeaveFormThatNeedsApproval",value:"Có 1 đơn nghỉ phép cần phê duyệt"},
    {key:"YourLeaveFormHasBeenApproved",value:"Đơn nghỉ phép của bạn đã được phê duyệt"},
    {key:"TheLeaveFormHasBeenApproved",value:"Đơn nghỉ phép đã được phê duyệt"},
    {key:"YourLeaveFormHasBeenRejected",value:"Đơn nghỉ phép của bạn đã bị bác bỏ"},
    {key:"TheLeaveFormHasBeenRejected",value:"Đơn nghỉ phép đã bị bác bỏ"},
    {key:"YouAreGrantedANewJourneyTimeForm",value:"Bạn vừa được cấp giấy đi đường"},
    {key:"YourJourneyTimeFormPermitApplicationHasBeenCancelled",value:"Giấy đi đường cho đơn nghỉ phép của bạn đã bị từ chối"},
    {key:"FlowDesign",value: "Thiết kế quy trình"},
    {key:"AddTaskWorkflow",value: "Thêm mới quy trình công việc"},
    {key:"UpdateTaskWorkflow",value: "Cập nhật quy trình công việc"},
    {key:"AddFolder",value: "Thêm Thư Mục"},
    {key:"AddFile",value: "Thêm Tệp Tin"},
    {key:"LastUpdate",value: "Cập nhập lần cuối"},
    {key:"FileSize",value: "Dung Lượng"},
    {key:"Version",value: "Phiên bản"},
    {key:"FolderEmpty",value: "Thư Mục Này Rỗng"},
    {key:"ShareFolder",value: "Chia Sẽ Thư Mục"},
    {key:"UpdateFolder",value: "Chỉnh Sửa Thư Mục"},
    {key:"UpdateFile",value: "Chỉnh Sửa Tệp Tin"},
    {key:"DoYouWantDeleteFolder",value: "Bạn có muốn xoá thư mục: {{name}}?"},
    {key:"DoYouWantDeleteFile",value: "Bạn có muốn xoá tệp tin: {{name}}?"},
    {key:"TaskName",value: "Tên công việc"},
    {key:"ClickToOpenThisTaskOnYourPortal",value: "Nhấn để xem chi tiết công việc trên cổng thông tin của bạn"},
    {key:"Return",value: "Trả lại"},
    {key:"Resubmit",value: "Tái trình ký"},
    {key:"Singed",value: "Đã ký"},
    {key:"Unsigned",value: "Chưa ký"},
    {key:"SignHistory",value: "Lịch sử ký"},
    {key:"Submitter",value: "Người trình ký"},
    {key:"WaitingForProgressing",value: "Đợi xử lý"},
    {key:"ExecutingASignature",value: "Thực hiện ký"},
    {key:"Are you sure you approve this document for signature",value: "Bạn có chắc chắn chấp thuận trình ký này không?"},
    {key:"Are you sure you confirm that received this",value: "Bạn có chắc chắn xác nhận đã nhận thông báo này không?"},
    {key:"Are you sure you reject this document for signature",value: "Bạn có chắc chắn bác bỏ văn bản trình ký này không?"},
    {key:"Are you sure you return this document for signature",value: "Bạn có chắc chắn trả lại trình ký này không?"},
    {key:"Are you sure you resubmit this document for signature",value: "Bạn có chắc chắn gửi lại văn bản trình ký này không?"},
    {key:"Are you sure you sign this document",value: "Bạn có chắc chắn ký văn bản trình ký {{filename}} này không?"},
    {key:"Format of signing in text",value: "Định dạng ký trong văn bản"},
    {key:"Permission: Role - Department",value: "Quyền hạn: {{role}} - {{department}}"},
    {key:"Import StudyPlan",value: "Nhập Lịch Học"},
    {key:"Import ExamSchedule",value: "Nhập Lịch Thi"},
    {key:"File Name",value: "Tên tệp"},
    {key:"Date Upload",value: "Ngày tải lên"},
    {key:"TaskManagement",value: "Quản lý công việc"},
    {key:"Download",value: "Tải xuống"},
    {key:"TemplateCustom",value:"Tập tin mẫu (Tuỳ chỉnh)"},
    {key:"FormatUploadedFile",value:"Định dạng file tải lên"},
    {key:"InputTagName",value:"Nhập tên thẻ"},
    {key:"Signing file (upload)",value:"Tập tin trình ký (tải lên)"},
    {key:"Signing file (auto generated)",value:"Tập tin trình ký (tạo tự động)"},
    {key:"Fill in the signing file information",value:"Điền thông tin tập tin trình ký"},
    {key:"Input content",value:"Nhập nội dung"},
    {key:"Preview",value:"Xem trước"},
    {key:"UpdateConfigTable",value: "Cập nhật thiết lập bảng"},
    {key:"Quotation mark",value:"Chữ ký nháy"},
    {key:"Text",value:"Chữ"},
    {key:"Signature",value:"Chữ ký"},
    {key:"Format",value:"Định dạng"},
    {key:"Select directory",value:"Chọn danh mục"},
    {key:"Signatures/Quotation marks cannot be duplicated in case All Approval",value:"Chữ ký/Chữ ký nháy không được trùng lặp khi loại phê duyệt là Đồng thuận"},
    {key:"Workflow is missing Signatures/Quotation marks",value:"Quy trình còn thiếu Chữ ký/Chữ ký nháy"},
    {key:"Created date",value:"Ngày tạo"},
    {key:"Created by",value:"Người tạo"},
    {key:"Content",value:"Nội dung"},
    {key:"Status",value:"Trạng thái"},
    {key:"Abbreviation",value:"Chữ viết tắt"},
    {key:"Input abbreviation",value:"Nhập chữ viết tắt"},
    {key:"AbbreviationIsExist",value:"Tên viết tắt đã tồn tại"},
    {key:"Code",value:"Mã"},
    {key:"File type",value:"Loại tệp tin"},
    {key:"File generated by template",value:"Tệp tin tạo theo mẫu"},
    {key:"User upload manually",value:"Người dùng tự tải lên"},
    {key:"Tag (in the file)",value:"Thẻ (trong tệp tin)"},
    {key:"Tag name",value:"Tên thẻ"},
    {key:"Tag type",value:"Loại thẻ"},
    {key:"e.g. sign_headofdep",value:"vd: chuky_truongphong"},
    {key:"Add Signature/Quotation mark tag",value:"Thêm thẻ Chữ ký/Chữ ký nháy"},
    {key:"Directory",value:"Danh mục"},
    {key:"Signing file require the following tags",value:"Tệp tin trình ký cần chứa các thẻ sau"},
    {key:"Task",value:"Công việc"},
    {key:"HeadTask",value:"Đầu việc"},
    {key:"Invalid file format",value:"Tệp tin không đúng định dạng"},
    {key:"File is missing required tags",value:"Tệp tin thiếu các thẻ cần có"},
    {key:"Create new Workflow play",value:"Thêm mới Trình ký"},
    {key:"GanttChart",value:"Biểu đồ Gantt"},
    {key:"Overview",value:"Tổng quan"},
    {key:"TaskAddNewNotification",value:"Thêm mới thông báo"},
    {key:"ThereIsANewProof",value:"Có một minh chứng mới"},
    {key:"ProofOfCompletion",value:"Minh chứng hoàn thành"},
    {key:"UpdateProofOfCompletion",value:"Tải lên minh chứng hoàn thành"},
    {key:"ProofFileRequired",value:"Cần có tệp minh chứng hoàn thành"},
    {key:"MaxProofFilesUpload",value:"Tối đa 5 tệp minh chứng được tải lên"},
    {key:"File size must not exceed", value: "Dung lượng tệp tin không vượt quá {{size}}"},
    {key:"TaskType",value:"Loại công việc"},
    {key:"All",value:"Tất cả"},
    {key:"Label",value:"Nhãn"},
    {key:"Department/Project",value:"Phòng ban/Dự án"},
    {key:"attachments/appendices",value:"Phụ lục/Hồ sơ đính kèm"},
    {key:"SearchByNameOrFileCode",value:"Tìm theo tên hoặc mã hồ sơ"},
    {key:"FileCode",value:"Mã hồ sơ"},
    {key:"CreationTime",value:"Thời gian hình thành"},
    {key:"ProfileDetails",value:"Thông tin chi tiết hồ sơ"},
    {key:"Are you sure you want to cancel this task?",value:"Bạn có chắn chắn muốn huỷ công việc này không?"},
    {key:"CancellationReason",value:"Lý do huỷ bỏ"},
    {key:"AllDepartments",value:"Tất cả phòng ban"},
    {key:"SomeDepartments",value:"Một số phòng ban"},
    {key:"Add Task by template for project",value:"Thêm mới công việc bằng template cho dự án"},
    {key:"Add Task by template for department",value:"Thêm mới công việc bằng template cho phòng ban"},
    {key:"LabelManagementForDepartment",value:"Quản lý các nhãn phòng ban"},
    {key:"AddNewMajorLabel",value:"Thêm mới nhãn lớn"},
    {key:"AddNewMinorLabel",value:"Thêm mới nhãn con"},
    {key:"UpdateMajorLabel",value:"Cập nhật nhãn lớn"},
    {key:"UpdateMinorLabel",value:"Cập nhật nhãn con"},
    {key:"NewTitleOfLabel",value:"Tên nhãn mới"},
    {key:"MajorLabel",value:"Tên nhãn lớn"},
    {key:"DownloadSampleFile",value:"Tải tệp tin mẫu"},
    {key:"IncommingDispatchBook",value:"Sổ công văn đến"},
    {key:"OutgoingDispatchBook",value:"Sổ công văn đi"},
    {key:"IntegrationWithWorkflowPlay",value:"Liên kết trình ký"},
    {key:"Early",value:"Sớm hạn"},
    {key:"Late",value:"Hoàn thành trễ hạn"},
    {key:"RecurringTask",value:"Công việc lặp lại"},
    {key:"Add recurring task for department",value:"Thêm công việc lặp lại của phòng ban"},
    {key:"Cycle",value:"Chu kỳ"},
    {key:"Series",value:"Chuỗi"},
    {key:"TaskManagementByCycle",value:"Quản lý công việc theo chu kỳ"},
    {key:"Pause",value:"Tạm dừng"},
    {key:"day",value:"ngày"},
    {key:"week",value:"tuần"},
    {key:"month",value:"tháng"},
    {key:"year",value:"năm"},
    {key:"PauseTask",value:"Tạm dừng công việc"},
    {key:"ResumeTask",value:"Tiếp tục công việc"},
    {key:"CancelTask",value:"Huỷ bỏ công việc"},
    {key:"Are you sure you want to resume this task?",value:"Bạn có chắc chắn muốn tiếp tục công việc này không?"},
    {key:"Are you sure you want to pause this task?",value:"Bạn có chắc chắn muốn tạm dừng công việc này không?"},
    {key:"TaskCode",value:"Mã công việc"},
    {key:"Year the briefcase was created",value:"Năm hình thành hồ sơ"},
    {key:"Add head task",value:"Thêm đầu việc"},
    {key:"HasBeenJustReleasedBy",value:"vừa được phát hành bởi"},
    {key:"WorkflowNodeOnSchedule", value: "Đúng Hạn"},
    {key:"WorkflowNodeGonnaLate", value: "Sắp trễ hạn"},
    {key:"WorkflowNodeOverDue", value: "Trễ hạn"},
    {key:"RequestCode",value:"Mã yêu cầu"},
    {key:"DocumentToBeCopied",value:"Văn bản cần sao y"},
    {key:"SentDate",value:"Ngày gửi"},
    {key:"UsageTime",value:"Thời gian sử dụng"},
    {key:"NormTime", value: "Thời gian định mức"},
    {key:"Deadline", value: "Hạn chót"},
    {key:"BusinessDay", value: "Ngày làm việc"},
    {key:"NotYet", value: "Chưa có"},
    {key:"Project", value: "Dự án"},
    {key:"Transfer ticket",value:"Phiếu chuyển"},
    {key:"HostPerson", value:"Người chủ trì"},
    {key:"Coordinator", value:"Người phối hợp"},
    {key:"SortBy", value:"Sắp xếp theo"},
    {key:"SortingOrder", value:"Cách sắp xếp"},
    {key:"Ascending(A->Z)", value:"Tăng dần (A->Z)"},
    {key:"Descending(Z->A)", value:"Giảm dần (Z->A)"},
    {key:"Are you sure you ack this event for",value: "Bạn có chắc chắn {{type}} sự kiện này cho mã sinh viên {{studentId}}?"},
    {key:"Document number and notation", value:"Số, ký hiệu văn bản"},
    {key:"Input Document number and notation", value:"Nhập Số, ký hiệu văn bản"},
    {key:"Agency promulgate", value:"Cơ quan ban hành"},
    {key:"Input Agency promulgate", value:"Nhập Cơ quan ban hành"},
    {key:"Department receives to know", value:"Đơn vị nhận để biết"},
    {key:"No department receives to know", value:"Không có đơn vị nhận để biết"},
    {key:"Selected", value:"Đã chọn"},
    {key:"Resolving tasks", value:"Đầu việc xử lý"},
    {key:"No resolving tasks", value:"Không có đầu việc xử lý"},
    {key:"Add resolving task", value:"Thêm đầu việc xử lý"},
    {key:"Task summary", value:"Mô tả công việc"},
    {key:"WaitingForApproval", value:"Chờ phê duyệt"},
    {key:"Edit", value:"Chỉnh sửa"},
    {key:"Forward to the head of the school office", value:"Chuyển đến lãnh đạo văn phòng trường"},
    {key:"Send to board of directors", value:"Xin ý kiến BGH"},
    {key:"Send to departments", value:"Chuyển xuống đơn vị"},
    {key:"Accept", value:"Chấp nhận"},
    {key:"Mark as read", value:"Đã xem"},
    {key:"ForwardToHeadOfOffice", value:"Chuyển đến Chánh văn phòng trường"},
    {key:"ForwardToBOD", value:"Xin ý kiến BGH"},
    {key:"WaitingForReview", value:"Chờ ý kiến BGH"},
    {key:"Transferred", value:"Đã chuyển"},
    {key:"WaitingForAccept", value:"Chờ chấp nhận"},
    {key:"Unread", value:"Chưa xem"},
    {key:"Read", value:"Đã xem"},
    {key:"ForwardToDepartments", value:"Chuyển xuống đơn vị"},
    {key:"ResponseRead", value:"Đã xem"},
    {key:"ResponseAccept", value:"Đã chấp nhận"},
    {key:"ResponseReject", value:"Đã trả lại"},
    {key:"You have an dispatch arrived _code_ that needs to be approved", value:"Bạn có một công văn đến {{code}} cần được phê duyệt"},
    {key:"You have an dispatch arrived _code_ that needs to be reviewed", value:"Bạn có một công văn đến {{code}} cần cho ý kiến"},
    {key:"ForwardNotifyToViewOnlyDepartments", value:"Bạn có một công văn đến {{code}} cần xem"},
    {key:"ForwardHeadTaskToDepartments", value:"Bạn có một công văn đến {{code}} cần được xử lý"},
    {key:"_department_ has accepted to process the dispatch arrived _code_", value:"{{department}} đã chấp nhận xử lý công văn đến {{code}}"},
    {key:"_department_ has rejected to process the dispatch arrived _code_", value:"{{department}} đã bác bỏ xử lý công văn đến {{code}}"},
    {key:"_department_ has read the dispatch arrived _code_", value:"{{department}} đã xem công văn đến {{code}}"},
    {key:"DoYouWantReleaseODB", value:"Bạn có muốn phát hành công văn đi này không?"},
    {key:"Attachment of the Incoming Document", value:"Tệp tin đính kèm của công văn đến "},
    {key:"Add Related File", value:"Thêm tệp tin liên quan"},
    {key:"ResponsibleWork", value:"Công việc chịu trách nhiệm"},
    {key:"CoordinationWork", value:"Công việc phối hợp"},
    {key:"SupervisionWork", value:"Công việc giám sát"},
    {key:"AllowsUsersToChooseTheDestination", value:"Cho phép người dùng chọn nơi nhận"},
    {key:"Handling methods", value:"Hình thức xử lý"},
    {key:"Flexible", value:"Linh động"},
    {key:"Fixed", value:"Cố định"},
    {key:"Confirm receipt of the notification", value:"Xác nhận đã nhận thông báo"},
    {key:"Grant permission to use the incoming dispatch feature", value:"Cấp quyền sử dụng tính năng công văn đến"},
    {key:"Right to view official dispatches other than work-related official dispatches", value:"Quyền xem các công văn ngoài các công văn liên quan đến công việc"},
    {key:"Only incoming dispatches related to assigned work can be viewed", value:"Chỉ được xem các công văn đến liên quan đến công việc được giao"},
    {key:"View official dispatches at the unit you are working at", value:"Xem các công văn tại đơn vị đang làm việc"},
    {key:"Dispatch belongs to all departments", value:"Công văn thuộc tất cả phòng ban"},
    {key:"Dispatches at some specific departments", value:"Công văn tại một số phòng ban cụ thể"},
    {key:"Not yet assigned", value:"Chưa phân công"},
    {key:"Input the submission department", value:"Nhập đơn vị soạn"},
    {key:"Car Name", value:"Tên xe"},
    {key:"License Plate", value:"Biển số xe"},
    {key:"Seating Capacity", value:"Chỗ ngồi"},
    {key:"UpdateCarInformation", value:"Chỉnh sửa thông tin của xe"},
    {key:"CarList", value:"Danh sách xe"},
    {key:"CarRegistration", value:"Đăng ký xe"},
    {key:"Destination", value:"Nơi đến"},
    {key:"Input Destination", value:"Nhập địa điểm đến"},
    {key:"Number of people", value:"Số lượng người"},
    {key:"Input Number of people", value:"Nhập số lượng người"},
    {key:"Start date", value:"Ngày bắt đầu"},
    {key:"End date", value:"Ngày kết thúc"},
    {key:"Back date", value:"Ngày trở về"},
    {key:"Department", value:"Phòng ban"},
    {key:"Description", value:"Ghi chú"},
    {key:"Register", value:"Người đăng ký"},
    {key:"CarReview", value:"Trưởng bộ phận phê duyệt"},
    {key:"CardDelivery", value:"Giao/nhận thẻ xe"},
    {key:"CarConfirm", value:"Duyệt xe/thẻ xe"},
    {key:"DoYouWantApprove", value: "Bạn có muốn duyệt chuyến xe {{title}} không?"},
    {key:"DoYouWantReject", value: "Bạn có muốn từ chối chuyến xe {{title}} không?"},
    {key:"DoYouWantClose", value: "Bạn có muốn kết thúc chuyến xe {{title}} không?"},
    {key:"carApprove", value: "Cấp thẻ xe"},
    {key:"manager_closed", value:"Đã kết thúc"},
    {key:"Closed", value: "Đã đóng"},
    {key:"Close", value:"Đóng"},
    {key:"end", value:"Kết thúc"},
    {key:"manager_approved", value:"Đã chấp thuận"},
    {key:"manager_reject", value:"Quản lý từ chối"},
    {key:"head_approved_car", value:"Đã đồng ý cấp xe"},
    {key:"head_approved_card", value:"Đã đồng ý cấp thẻ xe"},
    {key:"card_received", value:"Đã nhận thẻ xe"},
    {key:"reviewer_approved", value:"Đã xác nhận"},
    {key:"reviewer_rejected", value:"Trưởng bộ phận từ chối"},
    {key:"cancelled", value:"Đã hủy"},
    {key:"manager_card_received", value:"Đã nhận thẻ xe"},
    {key:"card_delivery", value:"Đã giao thẻ xe"},
    {key:"card_return", value:"Đã trả thẻ xe"},
    {key:"card_return_tooltip", value:"Trả thẻ"},
    {key:"card_delivery_tooltip", value:"Giao thẻ"},
    {key:"card_receive_tooltip", value:"Nhận thẻ"},
    {key:"cancel", value:"Hủy"},
    {key:"RejectReason", value:"Lý do từ chối:"},
    {key:"Card vehicle", value:"Chọn thẻ xe:"},
    {key:"Car", value:"Xe"},
    {key:"You dont have permission to do this", value:"Bạn không có quyền để thực hiện thao tác này"},
    {key:"Size", value:"Kích thước"},
    {key:"InsertMeetingRoom", value:"Thêm phòng họp"},
    {key:"UpdateMeetingRoom", value:"Cập nhật phòng họp"},
    {key:"IsUse", value:"Sử dụng"},
    {key:"UnUse", value:"Không sử dụng"},
    {key:"InputCodeOfMeetingRoom", value:"Nhập mã phòng họp"},
    {key:"InputTitleOfMeetingRoom", value:"Nhập tên phòng họp"},
    {key:"InputSizeOfMeetingRoom", value:"Nhập kích thước phòng họp"},
    {key:"InvalidRuleMeetingRoom", value:"Bạn không có quyền thực hiện thao tác này"},
    {key:"MeetingRoomSchedule", value:"Đăng ký lịch phòng"},
    {key:"CurrentLeadTasks", value:"Công việc chủ trì"},
    {key:"CarTicketManagement", value:"Quản lý xe / thẻ xe"},
    {key:"Need to review", value:"Cần xem qua"},
    {key:"started project", value:"đã bắt đầu dự án"},
    {key:"closed project", value:"đã đóng dự án"},
    {key:"RoomRegistration", value:"Đăng ký phòng họp"},
    {key:"LectureHallClassroom", value:"Giảng đường, phòng học"},
    { key: "AreYouSureYouApproveThisNotify", value: "Bạn có chắc chắn chấp thuận bản tin này không?" },
    { key: "AreYouSureYouRejectThisNotify", value: "Bạn có chắc chắn bác bỏ bản tin này không?" },
    {key:"PendingRecalled",value: "Đang xử lý thu hồi"},
    {key:"ApprovedRecallByDepartmentLeader",value: "Trưởng bộ phận đã duyệt thu hồi"},
    {key:"Recalled",value: "Đã thu hồi"},
    {key:"Recall",value: "Thu hồi"},
    {key:"ApprovedDate",value: "Ngày duyệt"},
    {key:"StatusProcess", value:"Trạng thái xử lý"},
    {key:"CreatedNotify", value:"Đã tạo bản tin"},
    {key:"RegisteredRecall", value:"Đã đăng ký thu hồi"},
    {key:"NewsType", value:"Loại bản tin"},
    {key:"NotificationRecipients", value:"Đối tượng gửi đến"},
    {key:"RejectRecall", value:"Bác bỏ thu hồi"},
    {key:"ApproveRecall", value:"Chấp thuận thu hồi"},
    {key:"ApproveRecallRequestForThisNotify", value:"Bạn có muốn chấp thuận yêu cầu thu hồi bản tin này không ?"},
    {key:"RejectRecallRequestForThisNotify", value:"Bạn có muốn bác bỏ yêu cầu thu hồi của bản tin {{title}} không ?"},
    {key:"InformationDepartment",value:"Thông tin phòng ban"},

    // event_calendar
    {key:"Participant", value:"Người tham dự"},
    {key:"PersonInCharge", value:"Người chủ trì"},
    {key:"Type", value:"Loại"},
    {key:"OfflineOnSite", value:"Công tác tại trường"},
    {key:"OfflineOffSite", value:"Công tác ngoài trường"},
    {key:"Online", value:"Trực tuyến"},
    {key:"CarRegister", value:"Đăng ký xe"},
    {key:"RoomRegister", value:"Đăng ký phòng"},
    {key:"EventCalendarRegister", value:"Đăng ký lịch công tác"},
    {key:"EventCalendarRegisterRecall", value:"Đăng ký thu hồi lịch công tác"},
    {key:"Location", value:"Địa diểm"},
    { key: "PendingApproval", value: "Chờ trưởng BP duyệt" },
    { key: "RejectedByDept", value: "Trưởng BP từ chối" },
    { key: "PendingApprovedByDept", value: " Chờ Trưởng BP khác duyệt" },
    { key: "RejectedByHeadDept", value: "BP khác từ chối" },
    { key: "PendingApprovedByHeadDept", value: "Chờ trưởng khoa duyệt" },
    { key: "FinalReject", value: "Từ chối bởi người phê duyệt cuối" },
    { key: "FinalApproval", value: "Đã duyệt - Hoàn thành" },
    { key: "Archived", value: "Đã lưu trữ" }  ,
    { key: "Loading", value: "Đang tải" },
    { key: "Registered", value: "Đã đăng ký" },
    { key: "DepartmentApproved", value: "Trưởng BP đã duyệt" },
    { key: "DepartmentApprovedRecall", value: "Trưởng BP đã duyệt thu hồi" },
    { key: "DepartmentReturned", value: "Trưởng BP trả lại" },
    { key: "DepartmentRejected", value: "Trưởng BP từ chối" },
    { key: "DepartmentRejectedRecall", value: "Trưởng BP từ chối thu hồi" },
    { key: "ManagerApproved", value: "Người quản lý lịch đã duyệt" },
    { key: "ManagerReturned", value: "Người quản lý lịch trả lại" },
    { key: "ManagerRejected", value: "Người quản lý lịch từ chối" },
    { key: "OrganizationApproved", value: "Người lãnh đạo đã duyệt" },
    { key: "OrganizationReturned", value: "Người lãnh đạo trả lại" },
    { key: "OrganizationReject", value: "Người lãnh đạo từ chối" },
    { key: "RequestCancel", value: "Yêu cầu hủy" },
    { key: "Cancelled", value: "Đã hủy" },
    { key: "MeetingLink", value: "Liên kết cuộc họp" },
    { key: "EventCalendar", value: "Lịch công tác" },
    { key: "EventManagement", value: "Đăng ký lịch công tác"},
    { key: "EventNeedToHandle", value: "Cần xử lý"},
    { key: "EventHandled", value: "Đã xử lý"},
    { key: "EventResponsibleUnit", value: "Thuộc đơn vị phụ trách"},
    { key: "EventCreated", value: "Đã tạo"},
    { key: "EventPersonallyInvolved", value: "Bản thân tham gia"},
    {key:"Task is already completed", value:"Công việc đã hoàn thành"},
    { key: "WorkTripCreation", value: "Đăng Ký" },
    { key: "WorkTripAll", value: "Tất cả" },
    { key: "WorkTripAssigned", value: "Cần xử lý" },
    { key: "FinalApprovalTitle", value: "Phê Duyệt Cuối - Trưởng Phòng" },
    { key: "RejectTitle", value: "Bạn có muốn từ chối lịch công tác này?" },
    { key: "ApprovalTitle", value: "Phê duyệt" },
    {key:"Task is cancelled", value:"Công việc đã bị hủy bỏ"},
    {key:"Task has not been started yet", value:"Công việc chưa được bắt đầu"},
    {key:"fast job processing", value:"xử lý nhanh công việc"},
    {key:"Document to be approved", value:"Văn bản cần ký duyệt"},
    {key:"Document Name/ Workflow Name", value:"Tên văn bản/ Tên quy trình"},
    {key:"Composer/Submitter", value:"Người soạn/Người trình ký"},
    {key:"Sign", value:"Ký"},
    {key:"Approve", value:"Chấp thuận"},
    {key:"FindDocumentByName", value:"Tìm văn bản bằng tên"},
    {key:"Processing time", value:"Hạn xử lý"},
    {key:"Responsible Department/Project", value:"Đơn vị/ dự án phụ trách"},
    {key:"Find task by name and code", value:"Tìm công việc theo tên và mã"},
    {key:"Challenge", value:"Khó khăn"},
    {key:"AddChallenge", value:"Thêm khó khăn"},
    {key:"AddChallengeSuccess", value:"Thêm khó khăn thành công"},
    {key:"AddChallengeAt", value:"thêm khó khăn vào lúc"},
    {key:"ChallengeResolved", value:"Khó khăn đã giải quyết"},
    {key:"GuidToResolveChallenge", value:"Hướng dẫn giải quyết khó khăn"},
    {key:"Add comment", value:"Thêm bình luận"},
    {key:"Display task of all departments", value:"Hiển thị công việc của tất cả đơn vị"},
    {key:"Default is only display task of departments youre leading", value:"Mặc định sẽ chỉ hiện thị các công việc của các phòng ban bạn lãnh đạo"},
    {key:"Latest comment", value:"Bình luận mới nhất"},
    {key:"DoYouWantReceiveCard", value:"Bạn có muốn xác nhận rằng đã nhận thẻ xe không?"},
    {key:"DoYouWantDeliveryCard", value:"Bạn có muốn giao thẻ xe không?"},
    {key:"DoYouWantReturnCard", value:"Bạn có muốn trả thẻ xe không?"},
    {key:"chooseDriver", value:"Chọn tài xế"},

    {key:"Grant permission to manage the incoming dispatch feature", value:"Quyền quản lý tính năng công văn đến"},
    {key:"Grant permission to lead the incoming dispatch feature", value:"Đóng vai trò lãnh đạo trong điều phối công văn đến"},
    {key:"This is the right for the organization s secretary", value:"Đây là quyền dành cho văn thư của tổ chức"},
    {key:"This is the right reserved for the organization s clerical leader", value:"Đây là quyền giành cho lãnh đạo văn thư của tổ chức"},
    {key:"Not allow", value:"Không được phép"},
    {key:"Right to approve in lead level", value:"Quyền phê duyệt ở cấp độ lãnh đạo"},
    {key:"For department is working", value:"Phòng ban đang làm việc"},
    {key:"All departments", value:"Tất cả phòng ban"},
    {key:"For specific departments", value:"Cho một vài phòng ban cụ thể"},
    {key:"This is the right reserved for board of directors", value:"Quyền gianh cho ban giám đốc"},
    {key:"Right to accept task", value:"Quyền xác nhận công việc từ công văn"},
    {key:"This is the right reserved for department leaders", value:"Đây là quyền giành cho lãnh đạo đơn vị"},
    {key:"Reminder of work due date", value:"Nhắc công việc đến hạn !!!"},
    {key:"Newsletter", value:"Bản tin"},
    {key:"Find newsletter by title", value:"Tìm bản tin theo tiêu đề"},
    {key:"Work schedule/ Meeting room/ Vehicle to be approved", value:"Lịch công tác/ Phòng họp/ Xe cần duyệt"},
    {key:"Find by title", value:"Tìm theo tiêu đề"},
    {key:"Find by title and code", value:"Tìm theo tiêu đề và mã"},
    {key:"YouHaveReminded", value:"Bạn đã nhắc nhở"},
    {key:"YouHaveNotReminded", value:"Bạn chưa nhắc nhở"},
    {key:"DeadlineReminder", value:"Nhắc hạn"},
    {key:"YouHaveCommented", value:"Bạn đã bình luận"},
    {key:"YouHaveNotCommented", value:"Bạn chưa bình luận"},
    {key:"ReminderSuccessful", value:"Nhắc hạn thành công"},
    {key:"YouJustCommented", value:"Bạn vừa bình luận"},
    {key:"Allow to approve event in depatment level", value:"Cho phép duyệt sự kiện ở cấp độ đơn vị"},
    {key:"CarCalendar", value:"Lịch xe/thẻ xe"},
    {key:"Car_Date", value:"Xe/ ngày"},
    {key:"enterTheAmountSpent", value:"Nhập số tiền chi tiêu"},
    {key:"invoice", value:"Hóa đơn"},
    {key:"isTrueInfoConfirm", value:"Xác nhận những thông tin trên là đúng sự thật"},

    {key:"Responsible Department", value:"Đơn vị phụ trách"},
    {key:"NumberOfParticipants", value:"Số lượng người tham gia"},

    //Registration room
    {key:"Confirmed", value:"Quản lí phòng đã duyệt"},
    {key:"Approved", value:"Đã duyệt"},
    {key:"ChooseRoom", value:"Chọn phòng"},
    {key:"Vehicle", value:"Xe"},
    {key:"WorkSchedule", value:"Lịch công tác"},
    {key:"PhoneNumber", value:"Số điện thoại"},
    {key:"SizeRoomNotEnough", value:"{{roomName}} chỉ có {{roomSize}} chỗ ngồi!"},
    {key:"RejectedRegistration", value:"Đã từ chối đăng ký!"},
    {key:"ApproredRegistration", value:"Đã duyệt đơn đăng ký"},
    {key:"Default is display all registration", value:"Mặc định sẽ hiển thị tất cả đăng ký"},
    {key:"ConfirmReject", value:"Xác nhận từ chối"},
    {key:"Delete", value:"Xóa"},
    {key:"TitleRegistrationRoom", value:"Tiêu đề cuộc họp"},
    {key:"Start date use", value:"Ngày bắt đầu sử dụng"},
    {key:"TypeRoom", value:"Loại phòng"},
    {key:"Room", value:"Phòng"},
    {key:"ParticipateDepartments", value:"Phòng ban tham dự"},
    {key:"OtherParticipants", value:"Người tham dự khác"},
    {key:"RejectApproval", value:"Từ chối phê duyệt"},
    {key:"ConfirmRequetCancel", value:"Xác nhận yêu cầu hủy"},
    {key:"ConfirmDelete", value:"Xác nhận xóa"},
    {key:"person", value:"người"},
    {key:"ConfirmedRoomRecall", value:"Quản lý phòng đã xác nhận thu hồi"},
    {key:"PersonAction", value:"Người thực hiện"},
    {key:"Action", value:"Hành động"},
    {key:"Reason", value:"Lý do"},
    {key:"Time", value:"Thời gian"},
    {key:"Title", value:"Tiêu đề"},

    {key:"ConfirmedEventCalendarRecall", value:"Quản lý đã xác nhận thu hồi"},
    {key:"RegisterEventCalendarSuccess", value:"Đăng ký lịch công tác thành công"},
    {key:"UpdateInfoSuccess", value:"Cập nhật thông tin thành công"},
    {key:"Deleted", value:"Đã xóa"},
    {key:"Requestcanceled", value:"Đã yêu cầu hủy"},
    {key:"NumdayShow", value:"Số ngày hiển thị"},

    {key:'ChooseDepartment',value:'Chọn phòng ban'},
    {key:'End date cannot be less than or equal to start date',value:'Ngày kết thúc không được nhỏ hơn hoặc bằng ngày bắt đầu'},
    {key:'RequestCancelSuccess',value:'Yêu cầu hủy thành công'},
    {key:'Accept registration successfully',value:'Đã phê duyệt đơn đăng kí'},
    {key:"NotToExceedDays", value:"Không được vượt quá {{numDay}} ngày"},
    {key:'ChooseHost', value:'Chọn người chủ trì'},
    {key:'AddOtherHost', value:'Thêm người chủ trì khác'},
    {key:'OtherHost', value:'Người chủ trì khác'},
    {key:'RecommendedService', value:'Yêu cầu phục vụ'},
    {key:'TechnicalSupport', value:'Hỗ trợ kĩ thuật'},
    {key:'TeaBreak', value:'Tea-break'},
    {key:'Flow', value:'Tiến trình'},
    {key:"approve", value:"Chấp thuận"},
    {key:"RegisterRoomSCheduleSuccess", value:"Đăng kí lịch phòng thành công"},
    {key:"UpdateRoomSCheduleSuccess", value:"Cập nhật thông tin đăng kí thành công"},
    {key:"Not choose room", value:"Chưa chọn phòng"},
    {key:"Rejected", value:"Đã từ chối"},
    {key:"Compose a news", value:"Tạo mới bản tin"},
    {key:"Temporary Department", value:"Phòng ban tạm"},
    {key:"Board", value:"Hội đồng"},
    {key:"Department Code", value:"Mã đơn vị"},
    {key:"You have run out of tasks to handle", value:"Bạn đã hết công việc cần xử lý"},
    {key:"Publish", value:"Phát hành"},
    {key:"Published", value:"Đã phát hành"},
    { key: "MarkAsComplete", value: "Đánh dấu hoàn tất" },

    {key:"CarRegistrationList", value:"Đăng ký xe"},
    {key:"Card not returned", value:"Chưa trả thẻ"},
    {key:"Pick up time", value:"Thời gian đón"},
    {key:"Time to go", value:"Thời gian đi"},
    {key:"Location List", value:"Danh sách địa điểm"},
    {key:"Location Name", value:"Tên địa điểm"},
    {key:"Starting place", value:"Nơi đi"},
    {key:"Passenger", value:"Hành khách"},
    {key:"Register car", value:"Đăng ký xe"},
    {key:"Department proposed", value:"Đơn vị đề xuất"},
    {key:"Department prepare content", value:"Đơn vị chuẩn bị nội dung"},
    {key:"Proposed", value:"Người đề xuất"},
    {key:"Participating departments", value:"Đơn vị tham gia"},
    {key:"Number of the participarnt must greater than or equal to", value: "Số người tham gia phải lớn hơn hoặc bằng {{number}}"},
    {key:"DepartmentLeaderApproved", value:"Trưởng bộ phận đã phê duyệt"},
    {key:"VehicleManagementSpecialistApproved", value:"Chuyên viên quản lý xe đã phê duyệt"},
    {key:"LeadApproved", value:"Lãnh đạo bộ phận quản lý đã phê duyệt"},
    {key:"CardManagerApproved", value:"Chuyển viên quản lý thẻ đã phê duyệt"},
    {key:"CardManagerAssignedCard", value:"Đã cấp thẻ"},
    {key:"DepartmentReceivedCard", value:"Bộ phận đăng ký đã nhận thẻ"},
    {key:"DepartmentReturnedCard", value:"Bộ phận đăng ký đã trả thẻ"},
    {key:"CompletedCard", value:"Đã hoàn tất"},
    {key:"RequestedRecall", value:"Đã yêu cầu thu hồi"},
    {key:"DepartmentLeaderApprovedRecall", value:"Trưởng bộ phận đã phê duyệt thu hồi"},
    {key:"VehicleManagementSpecialistApprovedRecall", value:"Chuyên viên quản lý xe đã phê duyệt thu hồi"},
    {key:"Pick up time cannot be less than or equal to time to go", value:"Thời gian đón không được nhỏ hơn thời gian đi"},
    {key:"AreYouSureApproveThisRegistration", value:"Bạn thật sự muốn chấp thuận đăng ký này ?"},
    {key:"AreYouSureEditCardCarThisRegistration", value:"Bạn thật sự muốn chỉnh sửa thẻ xe ?"},
    {key:"AreYouSureRejectThisRegistration", value:"Bạn thật sự muốn bác bỏ đăng ký này ?"},
    {key:"AreYouSureConfirmReturnCardCarThisRegistration", value:"Bạn thật sự muốn trả thẻ ?"},
    {key:"AreYouSureCancelThisRegistration", value:"Bạn thật sự muốn hủy đơn đăng ký này ?"},
    {key:"ProcessRegistration", value:"Xử lý đăng ký"},
    {key:"DeleteRegistration", value:"Xóa đăng ký"},
    {key:"You can note for accept", value:"Bạn cần ghi chú cho việc chấp thuận"},
    {key:"You need to note for request cancel", value:"Bạn cần ghi chú cho việc yêu cầu hủy"},
    {key:"You can note for edit card car", value:"Bạn cần ghi chú cho việc đổi thẻ"},
    {key:"You need to note for reject", value:"Bạn cần ghi chú cho việc bác bỏ"},
    {key:"You need to note for return card", value:"Bạn cần ghi chú cho việc trả thẻ"},
    {key:"You need to note for assign card", value:"Bạn cần ghi chú cho việc cấp thẻ"},
    {key:"You can note for receive card", value:"Bạn cần ghi chú cho việc nhận thẻ"},
    {key:"You need to note for cancel registration", value:"Ghi chú cho việc hủy đơn đăng ký"},
    {key:"You can note for return card", value:"Bạn cần ghi chú cho việc trả thẻ"},
    {key:"You can note for approval", value:"Bạn có thể ghi chú để phê duyệt"},
    {key:"Assign a car", value:"Cấp xe"},
    {key:"Assign a credit card", value:"Cấp thẻ xe/taxi"},
    {key:"Driver", value:"Tài xế"},
    {key:"Transportation allowance", value:"Chế độ đi lại"},
    {key:"CreditCard", value:"Thẻ xe/taxi"},
    {key:"CreditCardName", value:"Tên thẻ xe/taxi"},
    {key:"CreditCardNumber", value:"Số thẻ xe/taxi"},
    {key:"CreditCardBussy", value:"Đang được cho mượn"},
    {key:"CreditCardActive", value:"Đang sẵn sàng"},
    {key:"ChangeCardCredit", value:"Đổi thẻ xe/taxi"},
    {key:"ConfirmReceiveCard", value:"Xác nhận đã nhận thẻ"},
    {key:"AreYouSureConfirmReceiveCardCreditThisRegistration", value:"Bạn có chắc chắn xác nhận nhận thẻ xe/taxi không?"},
    {key:"ReturnCard", value:"Trả thẻ"},
    {key:"UploadFileInvoice", value:"Tải lên hình ảnh/chứng từ hóa đơn"},
    {key:"ICertifyThatTheAboveStatementsAreTrue", value:"Tôi xác nhận những thông tin trên là đúng sự thật"},
    {key:"TheAmountSpent", value:"Số tiền chi tiêu"},
    {key:"NumberKm", value:"Số km"},
    {key:"You can note for manager receive card", value:"Bạn có thể ghi chú cho việc nhận thẻ"},
    {key:"Input number card", value:"Nhập số thẻ"},
    {key:"Invoices", value:"Hóa đơn/chứng từ thanh toán"},
    {key:"AmountSpent", value:"Tiền chi tiêu"},
    {key:"Km", value:"km"},
    { key: "MarkAsCompleteSuccess", value: "Đánh dấu hoàn tất thành công" },
    { key: "MarkDone", value: "Đánh dấu làm xong" },
    {key:"MarkDoneSuccess", value:"Đánh dấu làm xong thành công"},

    {key:"ApprovedLeaderDepartment", value: "Trưởng phòng phê duyệt"},
    {key:"RejectedLeaderDepartment", value: "Trưởng phòng đã từ chối phê duyệt"},
    {key:"ApprovedCarManagement", value: "Quản lý thẻ xe đã phê duyệt"},
    {key:"RejectedCarManagement", value: "Quản lý thẻ/xe đã từ chối phê duyệt"},
    {key:"ApprovedLead", value: 'Lãnh đạo đã phê duyệt'},
    {key:"ApprovedRecallLead", value: 'Lãnh đạo đã phê duyệt thu hồi'},
    {key:"RejectedLead", value: "Lãnh đạo đã từ chối phê duyệt"},
    {key:"RejectedRecallLead", value: "Lãnh đạo đã từ chối phê duyệt thu hồi"},
    {key:"ApprovedCardManagement", value: "Quản lý thẻ đã phê duyệt"},
    {key:"RejectedCardManagement", value: "Quản lý thẻ đã từ chối phê duyệt"},
    {key:"CreatorReceivedCard", value: "Đã nhận thẻ"},
    {key:"CreatorReturnCard", value: "Đã trả thẻ"},
    {key:"ManagerReceivedCard", value: "Quản lý đã nhận lại thẻ"},
    {key:"CreatorCancel", value: "Đã hủy"},
    {key:"DepartmentApprovedCancel", value: "Trưởng BP đã duyệt yêu cầu hủy"},
    {key:"ShowMore", value: "Xem thêm"},
    {key:"CarScheduleUse", value: "Lịch sử dụng xe"},
    {key:"Allday", value: "Cả ngày"},
    {key:"Early in the day", value: "Đầu ngày"},
    {key:"Until the end of the day", value: "Hết ngày"},

    {key:"Need you to review and approve registration car", value: "Cần bạn xem qua và duyệt đơn đăng ký"},
    {key:"Department leader approved. Need you to review and confirm registration car", value: "Trưởng phòng đã duyệt. Cần bạn xem xét và xác nhận đơn đăng ký"},
    {key:"Manager car confirmed. Need you to review and approve registration car", value: "Quản lý thẻ/xe đã xác nhận. Cần bạn xem qua và duyệt đơn đăng ký"},
    {key:"Lead approved. Need you to review and approve registration car", value: "Trưởng BP đã duyệt. Cần bạn xem qua và duyệt đơn đăng ký"},
    {key:"Manager card approved. Need you to review and receive card credit", value: "Quản lý thẻ xe đã duyệt cần bạn xác nhận đã nhận thẻ"},
    {key:"Department returned card. Need you to review and confirm received card", value: "Bộ phận đăng ký đã trả thẻ. Cần bạn xem qua và xác nhận đã nhận lại thẻ"},
    {key:"approved the car registration", value: "đã phê duyệt đơn đăng ký"},
    {key:"Management card confirm received card credit", value: "Quản lý thẻ đã xác nhận nhận lại thẻ"},
    {key:"rejected the car registration", value: "Đã từ chối đơn đăng ký xe"},

    {key:"ManagementCarApproved", value: "Quản lý thẻ/xe đã duyệt"},
    {key:"ManagementCarRejected", value: "Quản lý thẻ/xe đã từ chối phê duyệt"},
    {key:"LeadRejected", value: "Lãnh đạo bộ phận đã từ chối phê duyệt"},
    {key:"ManagementCardApprove", value: "Quản lý thẻ đã phê duyệt"},
    {key:"ManagementCardRejected", value: "Quản lý thẻ đã từ chối phê duyệt"},
    {key:"ManagementCardChangeCard", value: "Quản lý thẻ đã đổi thẻ"},
    {key:"ManagementCardAssignCard", value: "Quản lý thẻ đã chọn thẻ"},
    {key:"CreatorReturnedCard", value: "Đã trả thẻ"},
    {key:"ManagingReceivedCard", value: "Quản lý thẻ đã nhận thẻ"},
    {key:"AreYouSureApprovalThisRegistration", value: "Bạn có chắc chắn phê duyệt đơn đăng ký này không?"},
    {key:"AreYouSureRequestCancelThisRegistration", value: "Bạn có chắc chắn yêu cầu hủy đơn đăng ký này không?"},
    {key:"AreYouSureApprovalRecallThisRegistration", value: "Bạn có chắc chắn duyệt yêu cầu thu hồi này không?"},
    {key:"AreYouSureRejectRecallThisRegistration", value: "Bạn có chắc chắn từ chối yêu cầu thu hồi này không?"},

    {key:"TimeEvent", value: "Thời gian bắt đầu"},
    {key:"AddressEvent", value: "Địa điểm/phòng họp"},
    {key:"DayEvent", value: "Thứ/Ngày"},
    {key:"Hour", value: "Giờ"},
    {key:"LevelEvent", value: "Cấp độ"},
    {key:"Level_1", value: "Toàn trường"},
    {key:"Level_2", value: "Trong phòng ban"},
    {key:"car", value: "Xe"},
    {key:"room", value: "Phòng họp"},
    {key:"event_calendar", value: "Lịch công tác"},
    {key:'State', value:'Tình trạng'},
    {key:'All Department', value:'Tất cả đơn vị'},

    {key:"registration_room_approve", value:"Đã duyệt"},
    {key:"registration_room_approve_recall",value:"Đã duyệt yêu cầu hủy"},
    {key:"registration_room_reject",value:"Đã từ chối"},
    {key:"registration_room_reject_recall",value:"Đã từ chối yêu cầu hủy"},
    {key:"registration_room_request_cancel",value:"Đã yêu cầu hủy"},
    {key:"registration_room_update",value:"Đã cập nhật thông tin"},
    {key:"registration_room_create",value:"Đã tạo"},

    {key:"Card/Car", value:"Thẻ/Xe"},
    {key:"Show column", value:"Cột hiển thị"},
    {key:"ChangeCar", value:"Đổi xe"},
    {key:"ChangeCard", value:"Đổi thẻ"},
    {key:"ChangeDriver", value:"Đổi tài xế"},
    {key:"LeadApprovedAndChange", value:"Trưởng BP đã duyệt và thay đổi"},
    {key:"LeadExternalApproved", value:"Lãnh đạo trường đã duyệt"},
    {key:"LeadExternalRejected", value:"Lãnh đạo trường đã từ chối"},
    {key:"DepartmentApprovedAndChange", value:"TP đã duyệt và thay đổi"},

    { key: 'ApproveTransferTicket', value: 'Chấp thuận phiếu chuyển' },
    { key: 'RejectTransferTicket', value: 'Từ chối phiếu chuyển' },
    { key: 'EditAndApprove', value: 'Chỉnh sửa và chấp thuận' },

    { key: 'I agree', value: 'Tôi đồng ý' },
    { key: 'I refuse', value: 'Tôi từ chối' },
    { key: 'Incorrect information', value: 'Sai thông tin' },
    { key: 'Out of cars', value: 'Hết xe' },
    { key: 'Out of cards', value: 'Hết thẻ' },
    { key: 'ManagementApproved', value: 'Quản lý phòng đã xác nhận' },
    { key: 'ManagementApprovedRecall', value: 'Quản lý phòng đã xác nhận thu hồi' },
    { key: 'ManagementRejected', value: 'Quản lý phòng đã từ chối' },
    { key: 'ManagementRejectedRecall', value: 'Quản lý phòng đã từ chối thu hồi' },
    { key: 'Lead external approved. Need you to review and receive card credit', value: 'Lãnh đạo đã duyệt. Bạn cần xem qua và nhận thẻ' },
    { key: 'addComment', value: 'Thêm bình luận' },
    { key: 'updateComment', value: 'Chỉnh sửa bình luận'},
    { key: 'I approve', value: 'Tôi chấp thuận' },
    { key: 'Well done, I approve', value: 'Làm tốt lắm, tôi chấp thuận' },
    { key: 'Processed', value: 'Đã xử lý' },
    { key: 'Done Approval', value: 'Phê duyệt làm xong' },
    { key: 'Complete Approval', value: 'Phê duyệt hoàn thành' },
    {key: "WorkIsRepeatedCyclically", value: "Công việc được lặp lại theo chu kỳ"},
    {key: "RoomCode", value: "Mã phòng"},
    {key: "RoomName", value:"Tên phòng"},
    { key: "WorkIsRepeatedCyclically", value: "Công việc được lặp lại theo chu kỳ"},
    { key: "Start", value: "Bắt đầu"},
    { key: "End", value: "Kết thúc"},
    { key: "Comment", value: "Bình luận"},
    { key: "There is a news notify that has not been viewed yet", value: "Bạn có một bản tin mới chưa xem"},
    { key: "CarManagement", value: "Đăng ký xe"},
    { key: "Reject Recall", value: "Từ chối thu hồi"},
    { key: "My calendar", value: "Lịch của tôi"},
    { key: "NumberCard", value: "Số thẻ"},
    { key: "ManageExternal", value: "Quản lý toàn trường"},
    { key: "ExportToExcelManage", value: "Xuất file lịch toàn trường"},
];

