module.exports=[
    {key:"Me",value:"Tôi"},
    {key:"public",value:"Cộng đồng"},
    {key:"pending",value:"đang xử lý"},
    {key:"Events",value:"Các sự kiện"},
    {key:"created",value:"Đã tạo"},
    {key:"updated",value:"Đã cập nhật"},
    {key:"Project",value:"Dự án"},
    {key:"NewProject",value:"Thêm mới dự án"},
    {key:"WikiNew",value:"Thêm mới Wiki"},
    {key:"WikiUpdate",value:"Cập nhật Wiki"},
    {key:"DBName",value:"Tên Database"},
    {key:"Collection",value:"Collection"},
    {key:"Time",value:"Thời gian"},
    {key:"WrittenBy",value:"Được soạn thảo bởi"},
    {key:"SaveBy",value:"được lưu bởi"},
    {key:"Name",value:"Tên"},
    {key:"Display",value:"Hiển thị"},
    {key:"DoYouWantToDeleteFollowData",value:"Bạn có muốn xoá các dữ liệu sau"},
    {key:"Activate",value:"Hoạt động"},
    {key:"Deactivate",value:"Vô hiệu hoá"},
    {key:"Branch",value:"Chi nhánh"},
    {key:"Competence",value:"Quyền hạn"},
    {key:"NotSelectedYet",value:"Chưa chọn"},
    {key:"Pick",value:"Chọn"},
    {key:"AttachedFile",value:"Tệp đã đính kèm"},
    {key:"UploadFile",value:"Tải tệp lên"},
    {key:"UploadFolder",value:"Tải thư mục lên"},
    {key:"DragTheFileHereToUpload",value:"Kéo tệp vào đây để tải lên"},
    {key:"DragTheFolderHereToUpload",value:"Kéo thư mục vào đây để tải lên"},
    {key:"TheFileWillAutomaticallyUploadWhenSelected",value:"Tệp sẽ tự động tải lên khi chọn"},
    {key:"UploadImage",value:"Tải ảnh lên"},
    {key:"DragTheImageHereToUpload",value:"Kéo ảnh vào đẩy để tải lên"},
    {key:"DetailsInformation",value:"Thông tin chi tiết"},
    {key:"Approval",value:"Chấp thuận"},
    {key:"Approve",value:"Duyệt"},
    {key:"SignOther",value:"Ký thừa lệnh"},
    {key:"Reject",value:"Bác bỏ"},
    {key:"Approving",value:"Đang phê duyệt"},
    {key:"Rejecting",value:"Đang bác bỏ"},
    {key:"SuccessApproval",value:"Đã chấp thuận"},
    {key:"SuccessReject",value:"Đã bác bỏ"},
    {key:"SuccessReturn",value:"Đã trả lại"},
    {key:"SuccessResubmit",value:"Đã gửi lại"},
    {key:"SuccessSign",value:"Thực hiện ký thành công"},
    {key:"All",value:"Tất cả"},
    {key:"Bookmark",value:"Đã lưu"},
    {key:"Pending",value:"Đang xử lý"},
    {key:"ApprovedByDepartmentLeader",value:"Trưởng bộ phận đã duyệt"},
    {key:"Spending",value:"Chi tiêu"},
    {key:"Processing",value:"Chưa hoàn thành"},
    {key:"PleaseCheckInformation",value:"Xin kiểm tra lại thông tin"},
    {key:"DataIsNull",value:"Dữ liệu không tồn tại"},
    {key:"ExistAccount",value:"Tài khoản đã được sử dụng"},
    {key:"Register",value:"Đăng ký"},
    {key:"Workflow",value:"Quy trình"},
    {key:"DocumentType",value:"Loại văn bản"},
    {key:"TypeName",value:"Tên loại"},
    {key:"TemplateFile",value:"Tệp tin mẫu"},
    {key:"ApprovalType",value:"Loại phê duyệt"},
    {key:"Signing",value:"Quy Trình"},
    {key:"WorkflowForMe",value:"Quy trình giành cho tôi"},
    {key:"FeaturePopular",value:"Tính năng thông dụng"},
    {key:"WorkflowPlay",value:"Quy Trình"},
    {key:"ApproverIsNull",value:"Người phê duyệt không tồn tại"},
    {key:"Created",value:"Đã tạo"},
    {key:"Updated",value:"Đã cập nhật"},
    {key:"Approved",value:"Đã phê duyệt"},
    {key:"ApprovedToCreate",value:"Đã phê duyệt khởi tạo"},
    {key:"Handled",value:"Đã xử lý"},
    {key:"Approver",value:"Người phê duyệt"},
    {key:"Rejected",value:"Đã bác bỏ"},
    {key:"Returned",value:"Đã trả lại"},
    {key:"SaveODB",value:"Đã lưu sổ công văn đi"},
    {key:"SaveBriefCase",value:"Đã lưu Hồ sơ"},
    {key:"transformSign",value:"Đã giao ký thừa lệnh cho"},
    {key:"NeedToHandle",value:"Cần xử lý"},
    {key:"FileSigning",value:"Tệp tin trình ký"},
    {key:"RelatedFile",value:"Tệp tin liên quan"},
    {key:"Note",value:"Ghi chú"},
    {key:"InputNote",value:"Nhập nội dung ghi chú"},
    {key:"YourLanguage",value:"Ngôn ngữ của bạn"},
    {key:"Task",value:"Công việc"},
    {key:"Assigned",value:"Được giao"},
    {key:"FromDate",value:"Từ ngày"},
    {key:"ToDate",value:"Đến ngày"},
    {key:"Grade",value:"Cấp"},
    {key:"MainPerson",value:"Người chịu trách nhiệm"},
    {key:"Participant",value:"Người tham gia"},
    {key:"Observer",value:"Người giám sát"},
    {key:"NotStartedYet",value:"Chưa bắt đầu"},
    {key:"Responsibility",value:"Chịu trách nhiệm"},
    {key:"StartDoing",value:"Bắt đầu thực hiện"},
    {key:"Completed",value:"Hoàn thành"},
    {key:"Unfinished",value:"Chưa hoàn thành"},
    {key:"Comment",value:"Bình luận"},
    {key:"PostAComment",value:"Đăng bình luận"},
    {key:"SuccessUpdating",value:"Cập nhật thành công"},
    {key:"LeaveForm",value:"Đơn nghỉ phép"},
    {key:"NumberOfDays",value:"Số ngày"},
    {key:"Reason",value:"Lý do"},
    {key:"days",value:"ngày"},
    {key:"DispatchArrived",value:"Công văn đến"},
    {key:"DispatchOutgoing",value:"Công văn đi"},
    {key:"DispatchArrivedType",value:"Tên loại"},
    {key:"DispatchArrivedBook",value:"Sổ công văn đến"},
    {key:"EmergencyLevel",value:"Độ khẩn"},
    {key:"ReceiveMethod",value:"Phương thức nhận"},
    {key:"SendMethod",value:"Phương thức gửi"},
    {key:"Excerpt",value:"Trích yếu"},
    {key:"DispatchArrivedDate",value:"Ngày chuyển"},
    {key:"Transfer date",value:"Ngày chuyển"},
    {key:"OutgoingDispatchBookDate",value:"Ngày công văn đi"},
    {key:"SaveDispatchBook",value:"Lưu sổ công văn"},
    {key:"DateMonthYearDocument",value:"Ngày tháng năm văn bản"},
    {key:"Author",value:"Tác giả"},
    {key:"UnitOrRecipientDocument",value:"Đơn vị hoặc người nhận văn bản"},
    {key:"ReleaseDate",value:"Thời gian phát hành"},
    {key:"PlaceOfDispatchArrived",value:"Nơi gửi"},
    {key:"TheSigner",value:"Người ký"},
    {key:"IsLegalDocument",value:"Là văn bản quy phạm pháp luật"},
    {key:"IsTheAssignmentDocument",value:"Là văn bản giao nhiệm vụ"},
    {key:"PeopleHandling",value:"Người xử lý"},
    {key:"AtLeast",value:"Nhỏ nhất là {{title}}"},
    {key:"Number",value:"Số"},
    {key:"Handling",value:"Xử trí"},
    {key:"Forward",value:"Chuyển tiếp"},
    {key:"AddTaskForThis",value:"Thêm công việc"},
    {key:"AddNotifyForThis",value:"Thêm thông báo"},
    {key:"NotRequired",value:"không bắt buộc"},
    {key:"InvalidInformation",value:"Thông tin không hợp lệ"},
    {key:"HandlingAndForward",value:"Xử lý và chuyển tiếp"},
    {key:"to",value:"đến"},
    {key:"Action",value:"Hành động"},
    {key:"Seen",value:"Đã xem"},
    {key:"NotSeen",value:"Chưa xem"},
    { key: "Employee", value: "Nhân viên" },
    {key:"WholeSchool",value:"Toàn trường"},
    {key:"Sent",value:"Đã gửi"},
    {key:"Notice",value:"Lưu ý"},
    {key:"Reportscanonlybesentfrom3amto9am",value:"Chỉ có thể gửi và chỉnh sửa báo cáo từ 3 giờ sáng đến 9 giờ sáng"},
    {key:"Reportscanonlybesentfromto",value:"Chỉ có thể gửi và chỉnh sửa báo cáo từ {{from}} giờ đến {{to}} giờ"},
    {key:"TotalNurse_Technicians",value:"Tổng số điều dưỡng/ kỹ thuật viên"},
    {key:"NurseReport",value:"Báo cáo điều dưỡng"},
    {key:"MyJourneyTimeForm",value:"Giấy đi đường của tôi"},
    {key:"ExceptTimeOnRoad",value:"Trừ thời gian đi đường"},
    {key:"AddJourneyTimeForm",value:"Tạo giấy đi đường"},
    {key:"CancelJourneyTimeForm",value:"Huỷ tạo giấy đi đường"},
    {key:"Cancel",value:"Huỷ"},
    {key:"AdministrativeNursing_Technicians",value:"Điều dưỡng/ kỹ thuật viên hành chính"},
    {key:"OutShiftNursing_Technicians",value:"Điều dưỡng/kỹ thuật viên ngoài tua trực"},
    {key:"NursingOutHospital",value:"Điều dưỡng ngoại viện"},
    {key:"MorningShiftNursing",value:"Điều dưỡng trực sáng"},
    {key:"AfternoonShiftNursing",value:"Điều dưỡng trực chiều"},
    {key:"NightShiftNursing",value:"Điều dưỡng trực đêm"},
    {key:"OverShiftNursing",value:"Điều dưỡng 24/24"},
    {key:"LeaveShiftNursing",value:"Điều dưỡng ra trực"},
    {key:"NursingAtClinic",value:"Điều dưỡng tại phòng khám"},
    {key:"LeaveNursing",value:"Điều dưỡng nghỉ phép"},
    {key:"MaternityLeaveNursing",value:"Điều dưỡng nghỉ hậu sản"},
    {key:"SickLeaveNursing",value:"Điều dưỡng nghỉ bệnh"},
    {key:"NursingGoSchool",value:"Điều dưỡng đi học"},
    {key:"ApprenticeNursing",value:"Điều dưỡng học việc"},
    {key:"ProbationaryNursing",value:"Điều dưỡng thử việc"},
    {key:"OtherCase",value:"Trường hợp khác"},
    {key:"RealBed",value:"Giường thực kê"},
    {key:"PatientNumber",value:"Tổng số bệnh nhân"},
    {key:"Level1Care",value:"Chăm sóc cấp 1"},
    {key:"FinalPhasePatient",value:"Bệnh nhân giai đoạn cuối"},
    {key:"VentilatorBase",value:"Cơ số máy thở"},
    {key:"ActiveVentilator",value:"Máy thở đang sử dụng"},
    {key:"MonitorBase",value:"Cơ số monitor"},
    {key:"ActiveMonitor",value:"Monitor đang sử dụng"},
    {key:"ElectricSyringeBase",value:"Cơ số bơm tiêm"},
    {key:"ActiveElectricSyringe",value:"Bơm tiêm đang sử dụng"},
    {key:"DropsCounterBase",value:"Cơ số máy đếm giọt"},
    {key:"ActiveDropsCounter",value:"Máy đếm giọt đang sử dụng"},
    {key:"General",value:"Chung"},
    {key:"Module",value:"Module"},
    {key:"Report",value:"Báo cáo"},
    {key:"Statistic",value:"Thống kê"},
    {key:"Date",value:"Ngày"},
    {key:"Sum",value:"Tổng"},
    {key:"ThingsNeedToHandle",value:"Công việc cần xử lý"},
    {key:"NotReportYet",value:"Chưa báo cáo"},
    {key:"LoadMoreNotify",value:"Tải thêm thông báo"},
    {key:"Password",value:"Mật khẩu"},
    {key:"NewPassword",value:"Mật khẩu mới"},
    {key:"RetypeNewPassword",value:"Nhập lại mật khẩu mới"},
    {key:"UpdateSuccessed",value:"Cập nhật thành công"},
    {key:"ChangePasswordSuccessed",value:"Thay đổi mật khẩu thành công"},
    {key:"TryToUseNewPassword",value:"Hãy sử dụng mật khẩu mới"},
    {key:"MyProfile",value:"Hồ sơ của tôi"},
    {key:"BasicSalary",value:"Lương cơ bản"},
    {key:"Salary",value:"Lương"},
    {key:"NumberOfHours",value:"Số giờ"},
    {key:"SalaryHours",value:"Giờ lương"},
    {key:"Hours",value:"Giờ"},
    {key:"Applicable for main person only",value:"Chỉ áp dụng cho người chịu trách nhiệm"},
    {key:"NotCompleted",value:"Chưa hoàn thành"},
    {key:"OutDeadline",value:"Trễ hạn"},
    {key:"Done",value:"Làm xong"},
    {key:"DoneDone",value:"Xong"},
    {key:"WaitingForApproval",value:"Chờ phê duyệt"},
    {key:"Approve",value:"Phê duyệt"},
    {key:"Close",value:"Đóng"},
    {key:"CreatedChildTask",value:"Đã thêm công việc con"},
    {key:"ChildTask",value:"Công việc con"},
    {key:"ParentTask",value:"Công việc cha"},
    {key:"Staff",value:"Nhân viên"},
    {key:"UpdatedInformation",value:"Đã cập nhật thông tin"},
    {key:"BirthDay",value:"Sinh nhật"},
    {key:"DateOfBirth",value:"Ngày sinh"},
    {key:"SelfDeclaration",value:"Tự khai báo"},
    {key:"EmployeeCode",value:"Mã nhân viên"},
    {key:"DuplicateData",value:"Dữ liệu trùng"},
    {key:"LoadedData",value:"Dữ liệu đã tải lên"},
    {key:"InvalidHandle",value:"Thao tác không hợp lệ"},
    {key:"YouHaveNotPermissionToPerformThisOperation",value:"Bạn không có quyền thực hiện thao tác này"},
    {key:"YouHaveNotPermissionToPerformThisOperationOrDataIsNotExists",value:"Bạn không có quyền thực hiện thao tác này hoặc dữ liệu không tồn tại"},
    {key:"ApprovedDataCannotBeDeleted",value:"Không thể xoá dữ liệu đã được phê duyệt"},
    {key:"NumberAndNotation",value:"Số, ký hiệu văn bản"},
    {key:"DateMonthYearDocument",value:"Ngày tháng năm văn bản"},
    {key:"ExpirationDate",value:"Thời hạn"},
    {key:"DispatchArrivedNumber",value:"Số đến"},
    {key:"Author",value:"Tác giả"},
    {key:"UnitOrRecipientDocument",value:"Đơn vị hoặc người nhận văn bản"},
    {key:"CantCreateAccountWithSystemUsername",value:"Không được tạo tài khoản với username hệ thống"},
    {key:"AddFriend",value:"Thêm bạn"},
    {key:"SearchYourFriendByIdOrName",value:"Tìm bạn bằng ID hoặc tên"},
    {key:"SearchResults",value:"Kết quả tìm kiếm"},
    {key:"FriendRequestHasBeenSent",value:"Lời mời kết bạn đã gửi"},
    {key:"FriendRequest",value:"Yêu cầu kết bạn"},
    {key:"FriendList",value:"Danh sách bạn bè"},
    {key:"SendMessage",value:"Gửi tin nhắn"},
    {key:"Customer",value:"Khách hàng"},
    {key:"NewCustomer",value:"Thêm khách hàng"},
    {key:"UpdateCustomer",value:"Cập nhật thông tin khách hàng"},
    {key:"Priority",value:"Độ ưu tiên"},
    {key:"Maintain",value:"Bảo trì"},
    {key:"Domain",value:"Tên miền"},
    {key:"Name",value:"Tên"},
    {key:"Module",value:"Module"},
    {key:"ContactPerson",value:"Người liên hệ"},
    {key:"Contract",value:"Hợp đồng"},
    {key:"NewContract",value:"Tạo mới hợp đồng"},
    {key:"UpdateContract",value:"Cập nhật thông tin hợp đồng"},
    {key:"UpdateContractExtension",value:"Cập nhật hợp đồng gia hạn"},
    {key:"PotentialContract",value:"Tiềm năng"},
    {key:"SpendingContract",value:"Chờ thanh toán"},
    {key:"CompletedContract",value:"Đã thanh toán"},
    {key:"MaintainContract",value:"Bảo trì"},
    {key:"TrashContract",value:"Xóa"},
    {key:"RegisterDate",value:"Ngày đăng ký"},
    {key:"Price",value:"Giá"},
    {key:"SetupCost",value:"Chi phí cài đặt"},
    {key:"PackageModule",value:"Gói sản phẩm"},
    {key:"ByMonth",value:"Theo tháng"},
    {key:"ByYear",value:"Theo năm"},
    {key:"ContractValue",value:"Giá trị hợp đồng"},
    {key:"ContractExtension",value:"Gia hạn hợp đồng"},
    {key:"Package",value:"Gói"},
    {key:"createdContract",value:"đã tạo hợp đồng"},
    {key:"updatedContract",value:"đã cập nhật thông tin hợp đồng"},
    {key:"makeExtension",value:"đã gia hạn hợp đồng"},
    {key:"updatedExtension",value:"đã cập nhật thông tin gia hạn hợp đồng"},
    {key:"Phone",value:"Số điện thoại"},
    {key:"UploadFeatureImage",value:"Kéo tệp vào đây để tải lên"},
    {key:"Product",value:"Sản phẩm"},
    {key:"Quantity",value:"Số lượng"},
    {key:"Draft",value:"Nháp"},
    {key:"ShareWithMe",value:"Chia Sẽ Với Tôi"},
    {key:"required",value:"bắt buộc"},
    {key:"Week",value:"Tuần"},
    {key:"Day",value:"Ngày"},
    {key:"Days",value:"Ngày"},
    {key:"Month",value:"Tháng"},
    {key:"Year",value:"Năm"},
    {key:"Quarter",value:"Quý"},
    {key:"Select",value:"Chọn"},
    {key:"StartDate",value:"Thời gian bắt đầu"},
    {key:"EndDate",value:"Thời gian kết thúc"},
    {key:"MoreInfo",value:"Xem thêm thông tin"},
    {key:"Notes",value:"Ghi chú"},
    {key:"Resource",value:"Nguồn lực"},
    {key:"Signed",value:"Đã ký"},
    {key:"Forwarded",value:"Đã chuyển tiếp"},
    {key:"PendingApproval",value:"Chờ chấp thuận"},
    {key:"SignedTransferTicket",value:"Đã ký phiếu chuyển"},
    {key:"Overdue",value:"Trễ hạn"},
    {key:"Open",value:"Còn hạn"},
    {key:"OnSchedule",value:"Đúng hạn"},
    {key:"GonnaLate",value:"Sắp tới hạn"},
    {key:"Early",value:"Sớm hạn"},
    {key:"Late",value:"Hoàn thành trễ hạn"},
    {key:"State",value:"Tình trạng"},
    {key:"AddProof",value:"Đã thêm minh chứng"},
    {key:"RemoveProof",value:"Đã xóa minh chứng"},
    {key:"RepeatEach",value:"Lặp lại mỗi {{amount}}"},
    {key:"EndsOn",value:"Kết thúc vào"},
    {key:"ConfirmProgress",value:"Xác nhận tiến độ"},
    {key:"WorkIsRepeatedCyclically",value:"Công việc được lặp lại theo chu kỳ"},
    {key:"End",value:"Kết thúc"},
    {key:"OnDay",value:"Vào ngày"},
    {key:"Never",value:"Không bao giờ"},
    {key:"ParticipantList",value:"Danh sách tham gia"},
    {key:"QRCode",value:"Mã QR"},
    {key:"StudentId",value:"Mã Sinh Viên"},
    {key:"ClassId",value:"Mã Lớp"},
    {key:"StudyProgramId",value:"Mã chương trình đào tạo"},
    {key:"CourseTime",value:"Khóa"},
    {key:"AckTrainingEventAction",value:"Đã {{action}} cho mã sinh viên {{studentId}}"},
    {key:"Briefcase", value: "Bìa hồ sơ"},
    {key:"BriefcaseTitle", value: "Tiêu đề bìa hồ sơ"},
    {key:"BriefcaseCode", value: "Mã hồ sơ"},
    {key:"NumberAndNotationOfBriefcase", value: "Số và ký hiệu hồ sơ"},
    {key:"IdentifierCodeOfTheAgencyOrOrganizationCompilingTheBriefcaseInventory", value: "Mã định danh của cơ quan, tổ chức lập danh mục hồ sơ"},
    {key:"UsageMode", value:"Chế độ sử dụng"},
    {key:"Language", value:"Ngôn ngữ"},
    {key:"StorageDuration", value:"Thời gian bảo quản"},
    {key:"TotalPageOfBriefcase", value:"Tổng số trang trong hồ sơ"},
    {key:"TotalDocumentOfBriefcase", value:"Tổng số văn bản trong hồ sơ"},
    {key:"day", value:"ngày"},
    {key:"month", value:"tháng"},
    {key:"year", value:"năm"},
    {key:"vi-VN", value:"tiếng Việt"},
    {key:"Note", value:"ghi chú"},
    {key:"Expired", value:"Hết hạn"},
    {key:"Warning", value:"Cảnh báo"},
    {key:"Info", value:"Thông báo"},
    {key:"Employees", value:"Nhân viên"},
    {key:"ProofOrCommentIsRequiredForTheTask", value:"Công việc cần có minh chứng hoặc bình luận để thay đổi sang đã 'Hoàn thành'"},
    {key:"CurrentTask", value:"Công việc hiện tại"},
    {key:"CompletedTask", value:"Công việc đã hoàn thành"},
    {key:"SubmissionDepartment", value:"Đơn vị soạn"},
    {key:"signedDate", value:"Ngày ký"},
    {key:"HostPerson", value:"Người chủ trì"},
    {key:"RecipientToKnowPerson", value:"Người nhận để biết"},
    {key:"NotPublicYet", value:"Chưa phát hành"},
    {key:"OrganizationEdit", value:"Đơn vị soạn"},
    {key:"Released", value:"Đã phát hành"},
    {key:"Message", value:"Thông điệp"},
    {key:"Dear", value:"Kính gửi"},
    {key:"Receiver", value:"Người nhận"},
    {key:"Release", value:"Phát hành"},
    {key:"SuccessExecuting", value:"Thực hiện thành công"},
    {key:"Executing...", value:"Đang thực hiện..."},
    {key:"ReceivingDepartment", value:"Phòng ban nhận"},
    {key:"DocumentNeedToBeExploited", value:"Văn bản cần khai thác"},
    {key:"SignToAcknowledge", value:"Ký nhận"},
    {key:"Are you sure you want to sign acknowledge?", value:"Bạn có chắc chắn muốn thực hiện ký?"},
    {key:"SignedToAcknowledge", value:"Đã ký nhận"},
    {key:"InputTitle", value:"Nhập tiêu đề"},
    {key:"InputAuthor", value:"Nhập tác giả"},
    {key:"InputNote", value:"Nhập ghi chú"},
    {key:"NumberCodeDocument", value:"Số, ký hiệu văn bản"},
    {key:"DateDocument", value:"Ngày tháng văn bản"},
    {key:"TypeDocumentAndExcerpt", value:"Tên loại và trích yếu nội dung văn bản"},
    {key:"ReceivingDocumentDepartment", value:"Nơi nhận văn bản"},
    {key:"OutgoingDocuments", value:"File văn bản đi"},
    {key:"AttachDocuments", value:"File đính kèm"},
    {key:"StorageName", value:"Tên kho lưu trữ"},
    {key:"StorageLocation", value:"Vị trí trong kho"},
    {key:"StorageType", value:"Loại kho"},
    {key:"RelatedInformation", value:"Thông tin liên quan"},
    {key:"TypeName", value:"Tên loại"},
    {key:"DocumentQuantity", value:"Số lượng văn bản"},
    {key:"TransferDate", value:"Ngày chuyển"},
    {key:"InvalidAction", value:"Hành động không hợp lệ"},
    {key:"ReceiverOrDepartmentNotificationIsRequired", value:"Người nhận hoặc phòng ban nhận cần được chọn"},
    {key:"InputQuantity", value:"Nhập số lượng"},
    {key:"PageNotFoundLine1", value:"Trang không tồn tại"},
    {key:"PageNotFoundLine2", value:"Trang bạn đang tìm kiếm không tồn tại hoặc bạn không có quyền truy cập vào trang này. Vui lòng liên hệ với quản trị viên để được hỗ trợ thêm."},
    {key:"NoPermissionLine1", value:"Truy cập bị từ chối"},
    {key:"NoPermissionLine2", value:"Xin lỗi, bạn không có quyền truy cập vào trang này. Vui lòng kiểm tra lại quyền truy cập hoặc liên hệ với quản trị viên để được hỗ trợ thêm."},
    {key:"CanNotAssignMultipleMainPerson", value:"Chỉ được phép giao một người chủ trì"},
    {key:"MainPersonRequired", value:"Người chủ trì không được để trống"},
    {key:"Input quantity", value:"Nhập số lượng"},
    {key:"DoYouWantReleaseODB", value:"Bạn có muốn phát hành sổ công văn đi không?"},
    {key:"ArrivedDate", value:"Ngày đến"},
    {key:"ReceivingUnit", value:"Đơn vị nhận"},
    {key:"BriefCase",value:"Hồ sơ"},
    {key:"NumberOfArrivedBook",value: "Số công văn đến"},
    {key:"OutgoingReferenceNumber",value: "Số công văn đi"},
    {key:"functionApply",value: "Chức năng áp dụng"},
    {key:"chooseColor",value: "Chọn Màu"},
    {key:"Fixed",value: "Cố định"},
    {key:"Flexible",value: "Linh hoạt"},
    {key:"Flexible",value: "Linh hoạt"},
    {key:"Handling methods",value: "Phương pháp xử lý"},
    {key:"Select an Option",value: "Chọn một lựa chọn"},
    {key:"Received",value:"Đã nhận"},
    {key:"TransactionNotificationReceived",value:"Đã nhận thông báo xử lý nghiệp vụ"},
    {key:"Automaticallycompletethetask",value:"Tự động kết thúc công việc"},
    {key:"ArchiveProfileComplete",value:"Hoàn thành hồ sơ lưu trữ"},
    {key:"task",value:"Công việc"},
    {key:"dispatch_arrived",value:"Công văn đến"},
    {key:"workflow_play",value:"Trình ký"},
    { key: "IsRepetitiveTask", value: "Là công việc lặp lại" },
    {key:"SendTo",value:"Gửi đến"},
    {key:"GeneralInformation",value:"Thông tin chung"},
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    { key: "ApproveForm", value: "Phê duyệt" },
    {key:"NeedToHandleLevel_1",value:"Lãnh đạo cần xử lý"},
    {key:"NeedToHandleLevel_2",value:"Trưởng bộ phận cần xử lý"},
    {key:"Scope",value:"Phạm vi"},
    {key:"External",value:"Ngoài đơn vị"},
    {key:"Internal",value:"Nội bộ"},
    {key:"InputReason", value:"Nhập lý do"},
    {key:"RecallReason", value:"Lý do thu hồi"},
    {key: "IsPersonal", value: "Quy trình dành cho cá nhân" },
    { key: "IsDepartment", value: "Quy trình dành cho phòng ban" },
    { key: "Handle", value: "Xử Lý" },
    {key: "ForPersonal", value: "Cá nhân" },
    {key: "ForDepartment", value: "Đơn vị phụ trách" },
    {key: "PersonalSignature", value: "Trình ký cá nhân" },
    { key: "DepartmentSignature", value: "Trình ký đơn vị" },
    { key: "This field is required", value: "Trường này bắt buộc" },
    { key: "PercentWork", value: "Phần trăm công việc" },
    { key: "PercentWorkRemaining", value: "Phần trăm công việc (còn lại: {{percentRemaining}})" },
    { key: "The total percent is 100. Please modify child tasks to create a new one!", value: "Phần trăm công việc là 100. Vui lòng chỉnh sửa công việc con để tạo mới!" },
    { key:"CreatedBy",value:"Được tạo bởi" },
    { key:"CreatedFrom", value:"Được tạo từ" },


];
