module.exports=[
    // key hệ thống
    {key:"Login",value:"Login"},
    {key:"SignUp",value:"Sign up"},
    {key:"SignInToYourAccount",value:"Signin to your Account"},
    {key:"InvalidSigninInformation",value:"Invalid Signin Information!"},
    {key:"ForgotPassword",value:"Forgot Password"},
    {key:"UserName",value:"Username"},
    {key:"PassWord",value:"Password"},
    {key:"RememberMe",value:"Remember"},

    {key:"DoYouWantDelete",value: "Do you want delete {{title}}?"},
    {key:"DoYouWantApprove",value: "Do you want approve {{title}}?"},
    { key: "DoYouWantReject", value: "Do you want reject {{title}}?" },
    {key:"DoYouWantRecall",value: "Do you want recall {{title}}?"},
    {key:"DoYouWantResetPassword",value: "Do you want reset password for account: {{title}}?"},
    {key:"DoYouWantThrowToRecyclebin",value: "Do you want throw {{title}} to recyclebin?"},
    { key: "DoYouWantRestoreFromRecyclebin", value: "Do you want restore {{title}} from recyclebin?" },
    {key:"DoYouWantRejectNotify",value: "Do you want reject notify?"},
    {key:"HomePage",value:"Home Page"},
    {key:"Menu",value:"Menu"},
    {key:"Group",value:"Group"},
    {key:"DepartmentGroup",value:"Department Group"},
    {key:"Rule",value:"Rule"},
    {key:"Role",value:"Role"},
    {key:"MenuGroup",value:"Menu group"},
    {key:"User",value:"User"},
    {key:"Appearance",value:"Appearance"},
    {key:"ValueOfAppearance",value:"Value of appearance"},
    {key:"Icon",value:"Icon"},
    {key:"QuickIcon",value:"Quick Icon"},
    {key:"MenuGroup",value:"Group Menu"},
    {key:"Dashboard",value:"Dashboard"},
    {key:"Management",value:"Management"},
    {key:"LoginPage",value:"Login Page"},
    {key:"Settings",value:"Settings"},
    {key:"Youtube",value:"Youtube"},
    {key:"AdminPage",value:"Admin Page"},
    {key:"Administrator",value:"Administrator"},
    {key:"EmployeePage",value:"Employee"},
    {key:"Search",value:"Search"},
    {key:"SearchByKey",value:"Search base on keys"},
    {key:"MoreOptions",value:"More options"},
    {key:"Type",value:"Type"},
    {key:"Alert",value:"Alert"},
    {key:"Details",value:"Details"},
    {key:"DetailsInfo",value:"Details"},
    {key:"DataFilterOptions",value:"Data filter options"},
    {key:"AdvancedSearch", value: "Advanced search"},

    {key:"NewGroup",value:"New Group"},
    {key:"Features",value:"FEATURES"},
    {key:"NewMenu",value:"New Menu"},
    {key:"NewMenuGroup",value:"New Menu Group"},
    {key:"NewQuickIcon",value:"New Quick Icon"},
    {key:"NewRole",value:"New Role"},
    {key:"NewRule",value:"New Rule"},
    {key:"RegisterUser",value:"Register A Account"},
    {key:"Welcome",value:"Welcome"},
    {key:"DoccumentManagement",value:"Doccument Management"},
    {key:"RecycleBin",value:"Recycle Bin"},
    {key:"History",value:"History"},
    {key:"MenuClose",value:"Close Menu"},
    {key:"DeleteAll",value:"DeleteAll"},
    {key:"RestoreAll",value:"RestoreAll"},
    {key:"Restore",value:"Restore"},

    {key:"OrderNumber",value:"Order Number"},
    {key:"Key",value:"Key"},
    {key:"Status",value:"Status"},
    {key:"ActiveStatus",value:"Active status"},
    {key:"IsActive",value:"Is Active"},
    {key:"Active",value:"Active"},
    {key:"InActive",value:"InActive"},
    {key:"Title",value:"Title"},
    {key:"DisplayName",value:"Display name"},
    {key:"Url",value:"Url"},
    {key:"Component",value:"Component"},
    {key:"Active",value:"Active"},

    {key:"QuickReport",value:"Quick report"},

    // Card List
    {key:"NewCard",value:"New Card"},
    {key:"Name",value:"Name"},
    {key:"Code",value:"Code"},
    {key:"UpdateCard",value:"Update Card"},
    {key:"ExistCode",value:"Exist Code"},

    // Home key
    {key:"InternalNotification",value:"Internal Notification"},
    {key:"WorkingTask",value:"Working Task"},
    {key:"MyWorking",value:"My Working"},
    {key:"MyParticipantWork",value:"My Participant Work"},
    {key:"MyObserveWork",value:"My Observe Work"},
    {key:"CreatedBy",value:"Created by"},
    {key:"SeeMore",value:"See more"},
    {key:"SeeLess",value:"See less"},

    // key cảnh báo
    {key:"NoMoreInformation",value:"No more information for {{title}}"},
    {key:"NoData",value:"No Data"},
    {key:"LoadDataFail",value:"Load data Fail!"},
    {key:"FailedAdding",value:"Create failure!"},
    {key:"SuccessAdding",value:"Create success!"},
    {key:"FailedSaving",value:"Update failed!"},
    {key:"SuccessSaving",value:"Update successful!"},
    {key:"FailedDeleting",value:"Delete failed!"},
    {key:"SuccessDeleting",value:"Successfully deleted!"},
    {key:"LoadPaginationFail",value:"Load Pagination Fail!"},
    {key:"NotEmpty",value:"Not Empty"},
    {key:"MustNotEmpty",value:"Must Not Empty"},
    {key:"ExistKey",value:"Exist Key."},
    {key:"MustMinIs1",value:"Must Min Is 1."},

    // key modal
    {key:"New",value:"New"},
    {key:"AddMore",value:"Add more"},
    {key:"Add",value:"Add"},
    {key:"UpdateMore",value:"Update More"},
    {key:"Retry",value:"Retry"},
    {key:"Close",value:"Close"},
    {key:"Delete",value:"Delete"},
    {key:"Save",value:"Save"},
    {key:"Saving",value:"Saving"},
    {key:"PreviousPage",value:"previous Page"},
    {key:"NextPage",value:"next Page"},
    {key:"Yes",value:"Yes"},
    {key:"No",value:"No"},
    {key:"Submit",value:"Submit"},
    {key:"InputKeyOfGroupGenu",value:"input key of group menu"},
    {key:"InputIconOfGroupMenu",value:"input icon of group menu"},
    // key Title

    {key:"InsertGroup",value:"Insert Group"},
    {key:"InsertMenu",value:"Insert Menu"},
    {key:"InsertMenuGroup",value:"Insert Group Menu"},
    {key:"MenuFilterData",value:"Menu Filter Data"},
    {key:"FilterwithActiveProperty",value:"Filter with Active Property"},
    {key:"MenuGroupData",value:"Menu Group Data"},
    {key:"MenuData",value:"Menu Data"},
    {key:"QuickIconData",value:"Quick Icon Data"},
    {key:"Description",value:"Description"},
    {key:"RoleInfomation",value:"RoleInfomation"},
    {key:"RuleInfomation",value:"RuleInfomation"},
    {key:"NewRootOrganization",value:"NewRootOrganization"},
    {key:"NewTechnique",value:"NewTechnique"},
    {key:"NewNotifyGroup",value:"NewNotifyGroup"},
    {key:"RegisterNotifyGroup",value:"RegisterNotifyGroup"},
    {key:"RoleData",value:"Role Data"},
    {key:"ConfigTable",value:"Config Table"},
    { key: "NavbarTitle", value: "ELECTRONIC OFFICE" },
    {key:"RegisterUserTemplate",value:"Register User Template"},
    {key:"Import user template sucess",value:"Import user template sucess!"},

];
