module.exports=[
    // key hệ thống
    {key:"Login",value:"Đăng nhập"},
    {key:"SignUp",value:"Đăng ký"},
    {key:"SignInToYourAccount",value:"Đăng nhập vào tài khoản của bạn"},
    {key:"InvalidSigninInformation",value:"Sai thông tin đăng nhập!"},
    {key:"ForgotPassword",value:"Quên mật khẩu"},
    {key:"UserName",value:"Tài khoản"},
    {key:"PassWord",value:"Mật khẩu"},
    {key:"RememberMe",value:"Ghi nhớ"},

    {"key":"DoYouWantDelete",value: "Bạn có muốn xóa {{title}} không?"},
    {"key":"DoYouWantApprove",value: "Bạn có muốn duyệt {{title}} không?"},
    { "key": "DoYouWantReject", value: "Bạn có muốn từ chối {{title}} không?" },
    {key:"DoYouWantRecall",value: "Bạn có muốn thu hồi {{title}} không?"},
    {key:"DoYouWantResetPassword",value: "Bạn có muốn reset mật khẩu cho tài khoản: {{title}}?"},
    {key:"DoYouWantResetPermission",value: "Bạn có muốn reset quyền cho tài khoản: {{title}}?"},
    {key:"DoYouWantThrowToRecyclebin",value: "Bạn có muốn bỏ {{title}} vào thùng rác không?"},
    {key:"DoYouWantRestoreFromRecyclebin",value: "Bạn có khôi phục {{title}} khỏi thùng rác không?"},
    {key:"DoYouWantRejectNotify",value: "Bạn có từ chối tin {{title}} không?"},
    {key:"HomePage",value:"Trang chủ"},
    {key:"Menu",value:"Menu"},
    {key:"Group",value:"Nhóm"},
    {key:"DepartmentGroup",value:"Nhóm phòng ban"},
    {key:"Rule",value:"Quyền"},
    {key:"Role",value:"Vai trò"},
    {key:"User",value:"Tài khoản"},
    {key:"MenuGroup",value:"Nhóm menu"},
    {key:"Appearance",value:"Style hiển thị"},
    {key:"ValueOfAppearance",value:"Giá trị style"},
    {key:"Icon",value:"Biểu tượng"},
    {key:"QuickIcon",value:"Tiện ích nhanh"},
    {key:"MenuGroup",value:"Nhóm menu"},
    {key:"Dashboard",value:"Tổng quan"},
    {key:"Management",value:"Quản trị"},
    {key:"LoginPage",value:"Trang đăng nhập"},
    {key:"Settings",value:"Thiết đặt"},
    {key:"Youtube",value:"Trang Youtube"},
    {key:"AdminPage",value:"Trang quản trị"},
    {key:"Administrator",value:"Người quản trị"},
    {key:"EmployeePage",value:"Trang Người dùng"},
    {key:"Search",value:"Tìm kiếm"},
    {key:"SearchByKey",value:"Tìm theo từ khóa"},
    {key:"MoreOptions",value:"Tùy chọn"},
    {key:"Type",value:"Loại"},
    {key:"Alert",value:"Cảnh báo"},
    {key:"Details",value:"Chi tiết"},
    {key:"DetailsInfo",value:"Thông tin chi tiết"},
    {key:"DataFilterOptions",value:"Tùy chọn lọc dữ liệu"},
    {key:"AdvancedSearch", value: "Tìm kiếm nâng cao"},

    {key:"NewGroup",value:"Tạo mới nhóm"},
    {key:"Features",value:"TÍNH NĂNG"},
    {key:"NewMenu",value:"Tạo mới menu"},
    {key:"NewMenuGroup",value:"Tạo mới nhóm menu"},
    {key:"NewQuickIcon",value:"Tạo mới tiện ích nhanh"},
    {key:"NewRole",value:"Tạo mới vai trò"},
    {key:"NewRule",value:"Tạo mới quyền"},
    {key:"RegisterUser",value:"Tạo mới tài khoản"},
    {key:"RegisterUserTemplate",value:"Tạo mới tài khoản hàng loạt"},
    {key:"Import user template sucess",value:"Tạo mới hàng loạt tài khoản thành công!"},
    {key:"Welcome",value:"Xin chào"},
    {key:"DoccumentManagement",value:"Quản lý nội dung"},
    {key:"RecycleBin",value:"Thùng rác"},
    {key:"History",value:"Lịch sử"},
    {key:"MenuClose",value:"Đóng menu"},
    {key:"DeleteAll",value:"DeleteAll"},
    {key:"RestoreAll",value:"RestoreAll"},
    {key:"Restore",value:"Khôi phục"},

    {key:"OrderNumber",value:"Số thứ tự"},
    {key:"Key",value:"Từ khóa"},
    {key:"Status",value:"Trạng thái"},
    {key:"ActiveStatus",value:"Trạng thái hoạt động"},
    {key:"IsActive",value:"Kích hoạt"},
    {key:"Active",value:"Hoạt động"},
    {key:"InActive",value:"Vô hiệu hóa"},
    {key:"Title",value:"Tiêu đề"},
    {key:"DisplayName",value:"Tên hiển thị"},
    {key:"Url",value:"Đường dẫn"},
    {key:"Component",value:"Thành phần"},
    {key:"Active",value:"Kích hoạt"},

    {key:"QuickReport",value:"Báo cáo nhanh"},

    // Card List
    {key:"NewCard",value:"Tạo mới thẻ"},
    {key:"Name",value:"Tên thẻ"},
    {key:"Code",value:"Mã thẻ"},
    {key:"UpdateCard",value:"Cập nhập card"},
    {key:"ExistCode",value:"Code đã tồn tại"},
    {key:"TaskCode",value:"Mã công việc"},

    // Home key
    {key:"InternalNotification",value:"bản tin nội bộ"},
    {key:"WorkingTask",value:"Công việc cần xử lý"},
    {key:"MyWorking",value:"Công việc của tôi"},
    {key:"MyParticipantWork",value:"Công việc tham gia"},
    {key:"MyObserveWork",value:"Công việc giám sát"},
    {key:"CreatedBy",value:"Được tạo bởi"},
    {key:"SeeMore",value:"Xem thêm"},
    {key:"SeeLess",value:"Thu gọn"},

    // key cảnh báo
    {key:"NoMoreInformation",value:"Chưa thêm thông tin nào cho {{title}}."},
    {key:"NoData",value:"Không có dữ liệu"},
    {key:"LoadDataFail",value:"Tải dữ liệu thất bại!"},
    {key:"FailedAdding",value:"Tạo mới thất bại!"},
    {key:"SuccessAdding",value:"Tạo mới thành công!"},
    {key:"FailedSaving",value:"Cập nhật thất bại!"},
    {key:"SuccessSaving",value:"Cập nhật thành công!"},
    {key:"FailedDeleting",value:"Xóa thất bại!"},
    {key:"SuccessDeleting",value:"Xóa thành công!"},
    {key:"LoadPaginationFail",value:"Tải thanh phân trang thất bại!"},
    {key:"NotEmpty",value:"Dữ liệu trống"},
    {key:"MustNotEmpty",value:"Không được để trống"},
    {key:"ExistKey",value:"Khóa tồn tại"},
    {key:"MustMinIs1",value:"Phải tối thiểu là 1."},

    // key modal
    {key:"New",value:"Thêm mới"},
    {key:"Add",value:"Thêm"},
    {key:"AddMore",value:"Tạo thêm"},
    {key:"UpdateMore",value:"Cập nhật thêm"},
    {key:"Retry",value:"Thử lại"},
    {key:"Close",value:"Đóng"},
    {key:"Delete",value:"Xóa"},
    {key:"Save",value:"Lưu"},
    {key:"Saving",value:"Đang lưu"},
    {key:"PreviousPage",value:"Trang trước"},
    {key:"NextPage",value:"Trang sau"},
    {key:"Yes",value:"Có"},
    {key:"No",value:"Không"},
    {key:"Submit",value:"Xác nhận"},

    {key:"InputKeyOfGroupGenu",value:"Nhập từ khóa nhóm menu"},
    {key:"InputIconOfGroupMenu",value:"Nhập icon của nhóm menu"},

    // key Title
    {key:"InsertGroup",value:"Thêm nhóm"},
    {key:"InsertMenu",value:"Thêm menu"},
    {key:"InsertMenuGroup",value:"Thêm nhóm menu"},
    {key:"MenuFilterData",value:"Lọc dữ liệu menu"},
    {key:"FilterwithActiveProperty",value:"Lọc với thuộc tính hoạt động"},
    {key:"MenuGroupData",value:"Dữ liệu nhóm menu"},
    {key:"MenuData",value:"Dữ liệu menu"},
    {key:"QuickIconData",value:"Dữ liệu tiện ích nhanh"},
    {key:"Description",value:"Mô tả"},
    {key:"RoleInfomation",value:"Thông tin vai trò"},
    {key:"RuleInfomation",value:"Thông tin quyền"},
    {key:"NewRootOrganization",value:"Thêm mới tổ chức"},
    {key:"NewTechnique",value:"Thêm mới chuyên môn"},
    {key:"NewNotifyGroup",value:"Thêm mới loại thông báo"},
    {key:"RegisterNotifyGroup",value:"Đăng ký loại thông báo"},
    {key:"RoleData",value:"Dữ liệu vai trò"},
    {key:"ConfigTable",value:"Chỉnh sửa bảng"},
    {key:"NavbarTitle",value:"VĂN PHÒNG ĐIỆN TỬ"},
];
