module.exports=[
    {key:"ExtendData",value:"Extend Data"},
    {key:"Value",value:"Value"},
    {key:"YourServiceIsUnregistered",value:"Your service is unregistered"},
    {key:"UserIsExists",value:"User is exists"},
    {key:"UpdateUserInformation",value:"Update user information"},
    {key:"DataIsActive",value:"Data is active"},
    {key:"Country",value:"Country"},
    {key:"Village",value:"Village"},
    {key:"ComputerSkills",value:"Computer skills"},
    {key:"EnglishLevel",value:"English level"},
    {key:"ProjectAndTask",value:"Project - task"},
    {key:"NoInformationHasBeenSelectedYet",value:"No information has been selected yet"},
    {key:"MasterDirectory",value:"Master directory"},
    {key:"Directory",value:"Directory"},
    {key:"DesignWorkflow",value:"Design workflow"},
    {key:"HumanResourceManagement",value:"Human resource management"},
    {key:"JourneyTimeForm",value:"Journey time form"},
    {key:"FindByName",value:"Find by name"},
    {key:"UpdateAccountGroupInformation",value:"Update account group information"},
    {key:"SelectedPart",value:"Selected part"},
    {key:"DoYouWantDeleteThisInformation",value:"Do you want delete this information"},
    {key:"DoYouWantRestoreThisInformation",value:"Do you want restore this information"},
    {key:"book_number",value:"Book Number"},
    {key:"from_number",value:"From number"},
    {key:"to_number",value:"To number"},
    {key:"grant_permission_for_storage",value:"Grant permission for storage"},
    {key:"InsertDepartmentGroup",value:"Insert Department Group"},
    {key:"Feature",value:"Feature"},
    {key:"FeatureName",value:"Feature name"},
    {key:"ApplyNewStorageFlow",value:"Apply new storage flow"},
    {key:"ApplyNewStorageFlowDescription",value:"When this feature is applied, the process of Outgoing Dispatch and Workflow play after storage will not be displayed"},
    {key:"FindByCode",value:"Find by code"},
    {key:"Document type",value:"Document type"},
    {key:"Year",value:"Year"},
    {key:"Going dispatch book type",value:"Going dispatch book type"},
    {key:"PersonInChargeOfLeadershipLevel",value:"Person in chare of leadership level"},
    {key:"PersonInChargeOfDepartmentLeadershipLevel",value:"Person in chare of department leadership level"},
    {key:"NotConfiguredYet",value:"Not configured yet"}
];
