module.exports=[
    {key:"ExtendData",value:"Phần dữ liệu mở rộng"},
    {key:"Value",value:"Giá trị"},
    {key:"YourServiceIsUnregistered",value:"Bạn chưa đăng ký dịch vụ này"},
    {key:"UserIsExists",value:"Tài khoản đã tồn tại{{username}}"},
    {key:"UpdateUserInformation",value:"Cập nhật thông tin tài khoản"},
    {key:"DataIsActive",value:"Dữ liệu đang trong trạng thái hoạt động"},
    {key:"Country",value:"Đất nước"},
    {key:"Village",value:"Thôn, làng"},
    {key:"ComputerSkills",value:"Trình độ tin học"},
    {key:"EnglishLevel",value:"Trình độ anh văn"},
    {key:"ProjectAndTask",value:"Dự án - công việc"},
    {key:"NoInformationHasBeenSelectedYet",value:"Chưa có thông tin nào được chọn"},
    {key:"MasterDirectory",value:"Danh sách danh mục"},
    {key:"Directory",value:"Danh mục"},
    {key:"DesignWorkflow",value:"Thiết kế quy trình"},
    {key:"HumanResourceManagement",value:"Quản lý nhân sự"},
    {key:"JourneyTimeForm",value:"Giấy đi đường"},
    {key:"FindByName",value:"Tìm theo tên"},
    {key:"UpdateAccountGroupInformation",value:"Cập nhật thông tin nhóm tài khoản"},
    {key:"SelectedPart",value:"Phần đã chọn"},
    {key:"DoYouWantDeleteThisInformation",value:"Bạn có muốn xoá thông tin này không"},
    {key:"DoYouWantRestoreThisInformation",value:"Bạn có muốn khôi phục thông tin này không"},
    {key:"book_number",value:"Quyển số"},
    {key:"from_number",value:"Từ số"},
    {key:"to_number",value:"Đến số"},
    {key:"grant_permission_for_storage",value:"Cấp quyền cho tính năng lưu trữ"},
    {key:"InsertDepartmentGroup",value:"Thêm mới nhóm phòng ban"},
    {key:"Feature",value:"Tính năng"},
    {key:"FeatureName",value:"Tên tính năng"},
    {key:"ApplyNewStorageFlow",value:"Áp dụng luồng lưu trữ mới"},
    {key:"ApplyNewStorageFlowDescription",value:"Khi tính năng này được áp dụng, quá trình của Công văn đi và Quy trình sau khi được lưu trữ sẽ không được hiện thị"},
    {key:"FindByCode",value:"Tìm theo mã"},
    {key:"Document type",value:"Loại văn bản"},
    {key:"Year",value:"Năm"},
    {key:"Going dispatch book type",value:"Loại số công văn đi"},
    {key:"PersonInChargeOfLeadershipLevel",value:"Người chịu trách nhiệm cấp lãnh đạo"},
    {key:"PersonInChargeOfDepartmentLeadershipLevel",value:"Người chịu trách nhiệm cấp đơn vị"},
    {key:"NotConfiguredYet",value:"Chưa cấu hình"}
];
