module.exports =[
    {key:"Profile",value:"Profile"},
    {key:"ChangePassword",value:"Change Password"},
    {key:"Signout",value:"Signout"},
    {key:"EditAvatar",value:"Edit Avata"},
    {key:"ProfilePhotoWillBChangedAutomatically",value:"Profile Photo Will Changed Automatically"},
    {key:"UploadNewPhoto",value:"Upload New Photo"},
    {key:"Update",value:"Update"},
    {key:"PersonalInfomation",value:"Personal Infomation"},
    {key:"PersonalStatistics",value:"Personal Statistics"},
    {key:"RecentNotifyReceived",value:"Recent Notify Received"},
    {key:"ViewMore",value:"View More"},
    {key:"Collapse",value:"Collapse"},
    {key:"RecentInfomations",value:"Recent Infomations"},
    {key:"MoreAccount",value:"More accounts"},
    {key:"AddAnotherAccount",value:"Add another account"},
    {key:"RecentlyLogged",value:"Recently logged in"},
    {key:"Click on your photo",value:"Click on your photo."},
    {key:"Remove account from this site",value:"Remove account from this site"},
];