module.exports =[
    {key:"Profile",value:"Thông tin của tôi"},
    {key:"ChangePassword",value:"Đổi mật khẩu"},
    {key:"Signout",value:"Đăng xuất"},
    {key:"EditAvatar",value:"Thay Avatar"},
    {key:"ProfilePhotoWillBChangedAutomatically",value:"Ảnh đại diện sẽ tự động thay đổi"},
    {key:"UploadNewPhoto",value:"Tải ảnh mới"},
    {key:"Update",value:"Cập nhật"},
    {key:"PersonalInfomation",value:"Hồ sơ của tôi"},
    {key:"PersonalStatistics",value:"Thống kê cá nhân"},
    {key:"RecentNotifyReceived",value:"Nhận thông tin gần đây"},
    {key:"ViewMore",value:"Xem thêm"},
    {key:"Collapse",value:"Thu Gọn"},
    {key:"RecentInfomations",value:"Thông tin gần đây"},
    {key:"MoreAccount",value:"Tài khoản khác"},
    {key:"AddAnotherAccount",value:"Thêm tài khoản khác"},
    {key:"RecentlyLogged",value:"Đăng nhập gần đây"},
    {key:"Click on your photo",value:"Nhấp vào ảnh của bạn."},
    {key:"Remove account from this site",value:"Gỡ tài khoản khỏi trang này"},
];